### ISSUE TITLE
MongoAuth: allow storing additional fields when creating users

### ISSUE THREAD

**Issue by DieterDePaepe** [eclipse-vertx/vertx-auth#102]
### Version

* vert.x core: 3.3.3
* vert.x auth: 3.3.3

### Context

MongoAuth provides a method to add a new User: 

    void insertUser(String username, String password, List<String> roles, List<String> permissions,
      Handler<AsyncResult<String>> resultHandler);

This approach does not provide any way to supply additional fields to the entry being saved. I suggest changing this method to add a JsonObject to which all data will be added before being stored:

    void insertUser(JsonObject template, String username, String password, List<String> roles, List<String> permissions,
      Handler<AsyncResult<String>> resultHandler);

**Comment by stefanvitz** [comment]
+1

**Comment by stefanvitz** [comment]
What is the the status here? 
When the team sees the value added on this one perhaps we could prepare an pull request.
the alternative is to work around in my code to insert a user via MongoAuth and then manually update the user with the needed data... (as any other user would have to do),,,

**Comment by pmlopes** [comment]
I'd say that if you're passing a json object template the template itself should already contain the username and password:

```java
void insertUser(JsonObject template, List<String> roles, List<String> permissions,
  Handler<AsyncResult<String>> resultHandler);
```

WDYT?

**Comment by pmlopes** [comment]
@stefanvitz feel free to discuss and make PRs

**Comment by DieterDePaepe** [comment]
@pmlopes I'd disagree for 2 reasons.

1) username and password are 2 things that MongoAuth tracks as special fields (MongoAuth knows which key they are stored under). So why merge username and password with the template, but leave out permissions and roles? Also, this would require the caller to also know the keys under which username and password are stored.

2) the password shouldn't be stored in the JSON. MongoAuth takes care of the hashing strategy and only stores the hash. Sure, it could replace the password out of the template and replace it with the hash, but that seems more error prone.

I'd suggest something like

```
void insertUser(JsonObject template, String username, String password, List<String> roles, List<String> permissions,  Handler<AsyncResult<String>> resultHandler) {
  //Throw error if username or password field are already specified in template
  //Throw error if roles/permissions are not null and are already specified in template
  //Functionality as it exists now.
}
```

I'm willing to make a PR if you agree with this approach and if you let me know what to do with the existing method? (Adjust it, remove it, leave it be)

**Comment by pmlopes** [comment]
The existing method should remain otherwise we break backwards compatibility. If you are willing so, please do a PR and document the flow as you described in the pseudo-code here since it is quite important to clarify what happens when the existing object already contains either username/password/permissions.

Now I think we should only throw error if the generated fields exists and are different from the mongoauth managed ones. Say if the username is the same it could be ok not to throw error but ignore and continue, same for roles/permissions **BUT** not for passwords, that should always be managed by the auth provider.

WDYT?

**Comment by DieterDePaepe** [comment]
Doing it that way is a bit more complicated, but it's reasonable. So, okay by me.

**Comment by pmlopes** [comment]
EU General Data Protection Regulation (GDPR) will start to be enforced in 2018 this PR will clearly link personal data with the collected data, so I'd not like to merge this and adding extra info to the user should be kept external as mandated by the GDPR.

**Comment by DieterDePaepe** [comment]
I fail to see the issue. Any realistic web application holds info linked to user accounts that isn't privacy related (time zone, preferred language, activation status of the account...).

Even if GDPR forbids this practice (after all, I'm no legal expert), it is the job of the application developer to be law compliant. This isn't the task of the framework...

**Comment by pmlopes** [comment]
@DieterDePaepe Is it is a matter of accountability. The end user can still use the backend collection with the columns at will but this is not declared by vert.x so in case of fines/sactions one cannot claim that this project is liable for the infringement.
