### ISSUE TITLE
add a simple htpasswd provider

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-auth#105]
Having a simple htpasswd provider would allow users to use a common file format instead of the custom properties file that will require the usage of apache shiro and blocking API.

This is not a full replacement for properties files since htpasswd only cover AuthN not AuthZ

**Comment by nevenr** [comment]
Hi Paulo,

can you assign this task to me.
Already I did some initial implementation.

Currently implementation is compatible with[ Apache 2.2 htpasswd file formats](https://httpd.apache.org/docs/2.2/misc/password_encryptions.html).
In [Apache 2.4 htpasswd file](https://httpd.apache.org/docs/2.4/misc/password_encryptions.html) [bcrypt](https://en.wikipedia.org/wiki/Bcrypt) format is introduced but I could not find java bcrypt lib that support latest bcrypt algorithm that Apache use. 

Regards,
N.

**Comment by pmlopes** [comment]
@nevenr I can only assign issues to the org members (github limitation).

**Comment by pmlopes** [comment]
However you can make a pull request so we can track that you're working on it.
