### ISSUE TITLE
Keycloak logout fails 

### ISSUE THREAD

**Issue by mavencode01** [eclipse-vertx/vertx-auth#108]
### Version
* vert.x auth: 3.4.0-SNAPSHOT

### Context

I encountered an exception while trying to add logout to my service using Keycloak provider. Any idea why ?

       ...
       oauth2 = KeycloakAuth.create(vertx, OAuth2FlowType.AUTH_CODE, config());
       ...

       private void logoutHandler(RoutingContext context) {
            
            JsonObject principal = context.user().principal();
            
            oauth2.getToken(principal, new Handler<AsyncResult<AccessToken>>() {
                
                @Override
                public void handle(AsyncResult<AccessToken> accessTokenResult) {
                    logger.info("Access token : {}", accessTokenResult.result());    //always null ???
                    accessTokenResult.result().logout(new Handler<AsyncResult<Void>>() {
                        
                        @Override
                        public void handle(AsyncResult<Void> logoutResult) {                                                    
                            context.clearUser();
                            context.session().destroy();
                            context.response().setStatusCode(204).end();
                            
                            logger.info("user logged out!");                            
                        }
                    });
                    
                }
            });
        }

**Comment by pmlopes** [comment]
You're requesting a token with an invalid state. The user object is the the access token you got from keycloak after login.

What you should do instead is:

```java
AccessToken acessToken = (AccessToken) context.user();
accessToken.logout(res -> {
  // do something after the call...
});
```

**Comment by mavencode01** [comment]
Fantastic! it works now.

Thanks
