### ISSUE TITLE
Use Oauth2FlowType.CLIENT is failed

### ISSUE THREAD

**Issue by zmyer** [eclipse-vertx/vertx-auth#112]
### Version

* vert.x core:3.3.3
* vert.x auth:3.3.3

### Context

In accordance with the examples you provide，I use OAuth2FlowType.CLIENT to get access_token in github， but it failed（"error":"bad_verification_code","error_description":"The code passed is incorrect or expired."），before starting, I have applied for Oauth Application in github. Client ID and Client Secret are right
Can you gvie me some suggetions.

**Comment by pmlopes** [comment]
I'm not sure if CLIENT is accepted by Github but AUTH_CODE should be. Make sure you use the right config:

```java
new OAuth2ClientOptions(httpClientOptions)
        .setSite("https://github.com/login")
        .setTokenPath("/oauth/access_token")
        .setAuthorizationPath("/oauth/authorize")
        .setClientID(clientId)
        .setClientSecret(clientSecret)
```

For 3.4 this will be simpler with:

```java
GithubAuth.create(vertx, clientId, clientSecret);
```

**Comment by zmyer** [comment]
@pmlopes , Would you give me a complete example that use AUTH_CODE, and how can you do to get authorization code and access token. In your case, there is no mention of how to get the user's authorization code，thanks

**Comment by pmlopes** [comment]
Please read the docs:

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-oauth2/src/main/asciidoc/java/index.adoc

And for a simpler approach use vertx-web:

https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/asciidoc/java/index.adoc#oauth2authhandler-handler
