### ISSUE TITLE
vertx-auth-jdbc update from 3.3.3 to 3.4.x

### ISSUE THREAD

**Issue by pcholder** [eclipse-vertx/vertx-auth#125]
I have OSGI environment. After update from 3.3.3 to 3.4.x i have issues with vertx-auth-jdbc. Now it requires vertx-rx-java, which requires reactivex, vertx.codegen, vertx.docgen, annotations, etc. Some of them do not have osgi compatibility.

**Comment by pmlopes** [comment]
`vertx-rx-java` is an optional dependency, you should be able to exclude it for now.

**Comment by pcholder** [comment]
But i still continue to receive this message:
```
org.osgi.framework.BundleException: Unable to resolve vertx-auth-jdbc [36](R 36.0): missing requirement [vertx-auth-jdbc [36](R 36.0)] osgi.wiring.package; (&(osgi.wiring.package=io.vertx.lang.rxjava)(version>=3.4.0)(!(version>=4.0.0))) Unresolved requirements: [[vertx-auth-jdbc [36](R 36.0)] osgi.wiring.package; (&(osgi.wiring.package=io.vertx.lang.rxjava)(version>=3.4.0)(!(version>=4.0.0)))]

```
Used jars: 
```
vertx-core-3.4.1.jar
vertx-sql-common-3.4.1.jar
vertx-auth-jdbc-3.4.1.jar
```

**Comment by cescoffier** [comment]
That's definitely a bug in the osgi metadata.

The metadata contains: `io.vertx.rxjava.*;resolution:=optional`. It should also contains: `io.vertx.lang.rxjava.*;resolution:=optional`. 

I'm surprised we didn't catch this....

**Comment by pcholder** [comment]
**vertx-auth-jwt** and **vertx-auth-oauth2** are also unable to be updated to 3.4.x, because of **vertx-jwt**

**Comment by pmlopes** [comment]
I'll mark this issue as invalid and close as the current version is 3.5.0 If this is still the case it can be re-open.
