### ISSUE TITLE
Google oauth do not get email and email_verified

### ISSUE THREAD

**Issue by nivg1992** [eclipse-vertx/vertx-auth#141]
### Version

* vert.x core: 3.4.1
* vert.x auth: 3.4.1

### Context

Hi,

I config on vertx google provider 

`oauth2Provider = OAuth2Auth.create(vertx, OAuth2FlowType.AUTH_CODE, credentials);`
`OAuth2AuthHandler oauth2 = OAuth2AuthHandler.create(oauth2Provider, CallbackURL);`
`oauth2.setupCallback(router.get("/callback"));`

route to redirect
`router.route("/loginprovide/google").handler(loginR::LoginWithGoogle);`

The procedure with google is success but after i get the access token and id_token,
I didn't get email and email_verified in JWT but other fields is received.

For example i received the fields (sub,aud,name,picture,given_name,family_name,locale)

Thanks for help,
Niv

**Comment by pmlopes** [comment]
Google will not give you the email directly you need to call their API:

https://developers.google.com/+/web/api/rest/latest/people/get
