### ISSUE TITLE
AccessToken should provide access to the underlying tokens

### ISSUE THREAD

**Issue by ghulands** [eclipse-vertx/vertx-auth#144]
### Version

* vert.x core: 3.4.1
* vert.x auth: 3.4.1

### Context

It would be good to be able to get access to the underlying json response data so that it can be stored in a database and reconstructed later. I can access it by casting to AccessTokenImpl, but I don't really like to do that when dealing with an interface.

**Comment by pmlopes** [comment]
You can get the underlying json object: http://vertx.io/docs/apidocs/io/vertx/ext/auth/User.html#principal--
