### ISSUE TITLE
Expose permissions array in JWTUser principal

### ISSUE THREAD

**Issue by kordian2k** [eclipse-vertx/vertx-auth#146]
### Version

* vert.x core: 3.4.1
* vert.x auth: 3.4.1

### Context
Given a JWTUser instance checking permissions would be easier if the permissions array is part of the principal. In fact, with the token being part of the principal the permissions are implicitly contained. Would it be possible to explicitly add the permissions?

**Comment by pmlopes** [comment]
@kordian2k could you elaborate with a code snippet how you would see this? I'm not really understanding what you want to achieve...

**Comment by kordian2k** [comment]
Dear @pmlopes,
Suppose a user is authenticated using vertx-web and its JWTAuthHandler. In my case the user may start a process running outside the JVM. Since I do not want to serialize / deserialize the user instance for future communication, I would like to generate a new short-living JWT including a different set of informations, but the same set of permissions.

**Comment by pmlopes** [comment]
You can get a JSON representation of the token by doing user.principal() in this case you can inspect and clone / modify the permissions. Isn't that a option for your problem?

**Comment by kordian2k** [comment]
Dear @pmlopes,
it is certainly an option. However, depending on the `permissionsClaimKey` in [JWTUser.java](https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWTUser.java) the stored permissions array is derived using the private method `getNestedJsonValue` which I would have to re-implement.

If you do not like the idea to change the `user.principal()`, how about changing the method signature of `getNestedJsonValue` from `private void` into `public static JsonArray` and setting "this.permissions" inside the constructor instead of the method?

**Comment by pmlopes** [comment]
All data is now visible on the principal or attributes.
