### ISSUE TITLE
JWT verification problem when using elliptic curve cryptography

### ISSUE THREAD

**Issue by kordian2k** [eclipse-vertx/vertx-auth#147]
### Version

* vert.x core: 3.4.2
* vert.x auth: 3.4.2

### Context
I encountered a verification problem w/ JWT tokens generated using Vert.x and verified using the python package [PyJWT](https://github.com/jpadilla/pyjwt). Generating token w/ PyJWT and verifying using Vert.x leads to a similar error.

The problem only exists when using elliptic curve cryptography (`ES512`). 

### Do you have a reproducer?

* https://github.com/kordian2k/jwt_elliptic_error

### Steps to reproduce
The reproducer constructs a *docker image* based on Debian Jesse. Prerequisites are a working docker installation. Moreover, the user running docker must have rights to run wo/ using `sudo` (e.g. by adding the user to the docker group).

1. `mvn package`
2. `docker run -it <image_id>`

### Extra
I understand the problems when using ECC w/ OpenJDK on which the docker image is based. However, a similar image running on **Hotspot** does not change behavior.

I do not know if the problem comes from Vert.x or PyJWT. However, it appears PyJWT was it least tested against a [Ruby implementation](https://github.com/jpadilla/pyjwt/issues/168). In general it would be desirable to have a compatible implementation.

**Comment by pmlopes** [comment]
`ECC` is only available on OracleJDK and restricted to export laws, Nevertheless I'll check it out

**Comment by pmlopes** [comment]
JCE Elliptic Curve signatures are in `ASN.1`/`DER` format while the JWT spec states that for `EC` algorithms the signature should be the values `R + S` as a concatenated byte representation of the 2 values.

**Comment by pmlopes** [comment]
@kordian2k I've added a compatibility test for `ECDSA` signatures generated from `Python` and `node`. Could you please verify.

**Comment by kordian2k** [comment]
@pmlopes I've tested the commit, but I still get a strange result:

**When using the attached keys and the commit the following works in vertx:**
`JWT jwt = new JWT().addPublicKey("ES512", "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEv5BsCYpLrE0qfDUWjWqXh3ABcI8JIw9A3e2sDSVN+wt102IttWiV7MFL06ch+JbFiIWxOahjaauKn+16aajEaw==");`

`assertFalse(jwt.isUnsecure());`

`assertNotNull(jwt.decode("eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9.eyJ1c2VybmFtZSI6InNvbWVib2R5Iiwic29tZSI6InBheWxvYWQiLCJpYXQiOjE0OTg4MzAxNDl9.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFPhYxqZVP-qK5nvJBzHMko4KlivuYQ1znGY0LjQyQaFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMpXkuHAzQqUXXDd2vEKmwz7PmWFalNmK2PZ9c2kbmd"));`

`assertNotNull(jwt.decode("eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9.eyJzb21lIjoicGF5bG9hZCIsInVzZXJuYW1lIjoic29tZWJvZHkifQ.A9V8cuK2J1GTPGJr4Jk63FOvVbJUz9paM1EqMkxMQjnHPe26oxL15FJxXZ4upHuHQzn3OO7GfH46kF08r5UjoA"));`

The first decoded a token was generated by Vertx, the second by PyJWT.

**Wenn using the attached keys with PyJWT and the same tokens**

`import jwt`

`jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9.eyJzb21lIjoicGF5bG9hZCIsInVzZXJuYW1lIjoic29tZWJvZHkifQ.A9V8cuK2J1GTPGJr4Jk63FOvVbJUz9paM1EqMkxMQjnHPe26oxL15FJxXZ4upHuHQzn3OO7GfH46kF08r5UjoA', '-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEv5BsCYpLrE0qfDUWjWqXh3ABcI8J\nIw9A3e2sDSVN+wt102IttWiV7MFL06ch+JbFiIWxOahjaauKn+16aajEaw==\n-----END PUBLIC KEY-----\n')
`

`jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9.eyJ1c2VybmFtZSI6InNvbWVib2R5Iiwic29tZSI6InBheWxvYWQiLCJpYXQiOjE0OTg4MzAxNDl9.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFPhYxqZVP-qK5nvJBzHMko4KlivuYQ1znGY0LjQyQaFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMpXkuHAzQqUXXDd2vEKmwz7PmWFalNmK2PZ9c2kbmd', '-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEv5BsCYpLrE0qfDUWjWqXh3ABcI8J\nIw9A3e2sDSVN+wt102IttWiV7MFL06ch+JbFiIWxOahjaauKn+16aajEaw==\n-----END PUBLIC KEY-----\n')
`

`jwt.decode('eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9.eyJ1c2VybmFtZSI6InNvbWVib2R5Iiwic29tZSI6InBheWxvYWQiLCJpYXQiOjE0OTg4MzAxNDl9.AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFPhYxqZVP-qK5nvJBzHMko4KlivuYQ1znGY0LjQyQaFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMpXkuHAzQqUXXDd2vEKmwz7PmWFalNmK2PZ9c2kbmd', verify=False)`

The first and the last command work, but the middle command verifying the token generated by Vertx fails with
```
envs/mqtt/lib/python3.6/site-packages/jwt/api_jws.py", line 196, in _verify_signature
    raise DecodeError('Signature verification failed')
jwt.exceptions.DecodeError: Signature verification failed
```

[keys.zip](https://github.com/vert-x3/vertx-auth/files/1115501/keys.zip)

**Comment by pmlopes** [comment]
Verifying ECDSA keys is tricky because the signature algorithm always initializes with a random seed so signature are not byte by byte equal but one needs to extract the R and S values and compare those.

I'll try to make a test for that and see what happened, of course tokens generated in vertx require a private key that is pair with the public one used to decode.

**Comment by pmlopes** [comment]
@kordian2k I've added a test using node to consume tokens generated from vert.x and I can verify that it works.

**Comment by kordian2k** [comment]
@pmlopes I think I have found the reason for the errors.
According to [RFC7518 (3.1)](https://tools.ietf.org/html/rfc7518) the signature algorithm should be as follows:

- ES256        | ECDSA using P-256 and SHA-256
- ES384        | ECDSA using P-384 and SHA-384
- ES5**12**        | ECDSA using P-5**21** and SHA-512

I made the mistake to use the keytool with parameters `-keyalg EC -keysize 256` which uses the curve "prime256v1". However, for ES384 and ES512 the options `-keysize 384` resp. `-keysize 521` have to be applied in order to use the curve "secp384r1" resp. "secp521r1".

With the correct keys everything works fine with this commit!

I have two remaining questions:

1. Would it be possible to adjust the suggested keysize parameters in the vertx documentation under [Generate a new Keystore file](http://vertx.io/docs/vertx-auth-jwt/java/)?
2. For me it feels misleading that you can apply `JWT#sign` for ES512 with a 256 key. Would it be possible to raise an error / a warning in that case? A similar strategy is used in [ruby-jwt  sign_ecdsa](https://github.com/jwt/ruby-jwt/blob/master/lib/jwt/signature.rb).

**Comment by pmlopes** [comment]
PR updated with correct key sizes. And indeed we can probably open a new issue to validate the size of the signatures and the algorithm names.

**Comment by pmlopes** [comment]
Also I plan to update the documentation to explain how to generate the keys using `openssl` too.
