### ISSUE TITLE
AccessToken.refresh error

### ISSUE THREAD

**Issue by johnoliver** [eclipse-vertx/vertx-auth#153]
### Version

* vert.x auth: 3.4.2

### Context

When calling AccessToken.refresh I get the following error:

```
Cannot supply multiple client credentials. Use one of the following: credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body
```

Seems like `AccessTokenImpl.refresh` needs to add `put("authorizationHeaderOnly", true)` to the api query, similar to the `AccessTokenImpl.introspect` method. 

Would adding this break other applications?

**Comment by pmlopes** [comment]
I don't believe it will break anything.
