### ISSUE TITLE
JWT-Auth "now" is truncating instead of rounding.

### ISSUE THREAD

**Issue by jwagnerLegacy** [eclipse-vertx/vertx-auth#157]
### Version

* vert.x core: 3.4.2
* vert.x auth: 3.4.2

### Context

I've noticed that when using Auth-JWT, sometimes the validation of the token fails because iat is greater than now (Current time in seconds). Everything else passes, but iat. I've noticed this behavior with Google's OAuth Implementation.

In testing I have deduced that Google is rounding their timestamp, while Java is truncating it. This results in Java's Timestamp sometimes being behind Google's.

Example:

Now in milliseconds (Obtained via `System.currentTimeMillis()`)
1504218035724

Google: 1504221636
Vertx: 1504218035

### Current Code Location

Vertx Truncates the time here:
https://github.com/vert-x3/vertx-auth/blob/8e5c0f5b42cd7531f864eae974a7aa42230c33d7/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWTAuthProviderImpl.java#L117

### Steps to reproduce 
(Unfortunately I'm not able to provide the code for reproduction. Company Property and all that.)

1. Do OAuth2 with Google to spec to get Token
2. Output the Token's decoded Payload
3. Output `System.currentTimeMillis()`
4. Compare the Payload's iat with current time.

### Suggested Fix
Round the time based on normal conventions (5 and up rounds up, 4 and under rounds down.)

**Comment by pmlopes** [comment]
Either Google is rounding (which it shouldn't since it means that you're setting times in the future) or the clocks between the two parties are drifting.

What I propose is to add a `leeway` default to 0 that will allow adjusting the current clock for sync issues. So if you would say allow leeway of 5 seconds the everything should be fine for you.
