### ISSUE TITLE
MongoAuth: Provide method for updating and/or encrypting password

### ISSUE THREAD

**Issue by jgeth** [eclipse-vertx/vertx-auth#160]
Currently, there is no mechanism provided by MongoAuth to update a principal's password. While it is possible to replicate the encryption strategy outside of MongoAuth, this presents potential for breaking if the strategy within MongoAuth is modified.

Request to provide a mechanism for updating a MongoAuth principal. If insertUser() expects an unencrypted String for password, a new method (updateUser()? updatePassword()?) should also expect an unencrypted String for password. Concurrently, the password encryption strategy should either be moved to a common private method or (if not providing an update method) exposed as a public method in order to update the principal outside of MongoAuth.

**Comment by pmlopes** [comment]
why not use your mongo client to do your user management and recalculate the hash by invoking:

```java
User user = ... // the mongo user you want to update
String password = ... // the new password

// has as required on the db
String hash = mongoAuth.getHashStrategy().computeHash(password, user);

mongo.update(...);
```

**Comment by jgeth** [comment]
Doing precisely this currently. Concern is that if MongoAuth implementation changes, external code needs to change. Maybe this is a non-issue, but a convenience method seems a safer approach.

**Comment by pmlopes** [comment]
The API used above is public so we should have the contract of not breaking it.

**Comment by jgeth** [comment]
Works for me
