### ISSUE TITLE
JWT decode issue

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-auth#168]
@neterium commented on [Thu Oct 26 2017](https://github.com/vert-x3/issues/issues/304)

Hi !

I'm using the vertx JWT auth provider, but I'm behind an API gateway which does all the signature checks etc.... for me already. So I basically use the provider to further (re)check the token expiration and to receive my User which will then be used for the authorization (role checks).

I noticed in the JWT.class code that the decode could be 'secure' or 'unsecure'; well that's fine, I'm unsecure in my case, but still got an exception, which should not be raised in my opinion:

`List<Crypto> cryptos = cryptoMap.get(alg);

    if (cryptos == null || cryptos.size() == 0) {
      throw new RuntimeException("Algorithm not supported");
    }

    // if we only allow secure alg, then none is not a valid option
    if (!unsecure && "none".equals(alg)) {
      throw new RuntimeException("Algorithm \"none\" not allowed");
    }`

In my case, 'cryptos' is null and I get that "Algorithm not supported" exception... But if in "unsecure" mode, 'cryptos' is not used anywhere and the JWT should just be decoded, checked and returned.

Thanks,

**Comment by pmlopes** [comment]
@neterium what you're seeing is correct. You are in unsecure mode when your JWT object does not have any keys/mac's configured, however your token header do specify that they are encoded using a specific algorithm. (it should be the "alg" variable you see).

Since there are no known keys for that algorithm the auth provider cannot confirm that the token is valid or not. Now you might wonder why don't we just assume unsecure if there are no keys for the algorithm, and the reason is that if we do that then we would suffer from the following:

https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by neterium-dev** [comment]
Well, I do not have "none" in my algo and the token is properly signed (RS256), but already verified in my API Gateway. Si, in other words, it would be nice to have a way to just skip the signature check. Maybe in the options? In the meantime, I've written my own authenticator; but I think it might be a good addition.
