### ISSUE TITLE
Working Kotlin example

### ISSUE THREAD

**Issue by adrianmoya** [eclipse-vertx/vertx-auth#171]
Is there a Kotlin example? I'm trying to get the docs example in http://vertx.io/docs/vertx-auth-jwt/kotlin/ but I just can't find the combination of imports to make it work. Java works out-of-the-box but I'm learning Kotlin. The example code is:

```
var config = JWTAuthOptions(
  keyStore = KeyStoreOptions(
    path = "keystore.jceks",
    password = "secret"))
```

**Comment by adrianmoya** [comment]
Actually, it looks like that's not valid Kotlin code? I made it work like this:

```
var config = JWTAuthOptions(
	JsonObject(mapOf(
		"keyStore" to KeyStoreOptions(JsonObject(mapOf(
		"path" to "keystore.jceks",
		"password" to "secret"
		)))
)))
```

**Comment by adrianmoya** [comment]
The code that finally worked was this:

```
var options = KeyStoreOptions().setPath("keystore.jceks").setPassword("secret")
var config = JWTAuthOptions().setKeyStore(options)
```

The original example from the docs gives the error 
```
None of the following functions can be called with the arguments supplied: public constructor JWTAuthOptions() 
 defined in io.vertx.ext.auth.jwt.JWTAuthOptions public constructor JWTAuthOptions(json: JsonObject!) defined in 
 io.vertx.ext.auth.jwt.JWTAuthOptions public constructor JWTAuthOptions(other: JWTAuthOptions!) defined in 
 io.vertx.ext.auth.jwt.JWTAuthOptions"
```

And using the constructor with the JsonObject failed with:
```
java.lang.RuntimeException: Algorithm not supported
	at io.vertx.ext.jwt.JWT.sign(JWT.java:373)
	at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.generateToken(JWTAuthProviderImpl.java:184)
```

**Comment by pmlopes** [comment]
I'm worked on a PR for key generation with examples: #191 feel free to review

**Comment by BrunoVernay** [comment]
I am trying to build one https://gitlab.com/BrunoVernay/oauth-vertx-kotlin 
It does not work yet, but it builds: dependencies and syntax are Ok.
