### ISSUE TITLE
JWTAuthHandler interface create cannot skip multiple paths

### ISSUE THREAD

**Issue by patton73** [eclipse-vertx/vertx-auth#174]
Version

    vert.x core: 3.5.0
    vert.x web: 3.5.0

The interface JWTAuthHandler create method
static JWTAuthHandler create(JWTAuth authProvider, String skip)

lacks the possibility to skip completely different path routes (for example /path1 /path2)
Could be very useful to add this possibility.
You can pass an ArrayList of String to be skipped.

Thank you very much for your help.
Andrea.

**Comment by pmlopes** [comment]
This is a web issue and the feature to skip has been deprecated a while ago. The correct way is to create the right matching for the secure paths.
