### ISSUE TITLE
ChainAuthHandlerImpl always authorizes authenticated users

### ISSUE THREAD

**Issue by cristic83** [eclipse-vertx/vertx-auth#183]
### Version

* vert.x core: 3.5.0
* vert.x auth: 3.5.0

### Context

The chaining of multiple auth mechanisms does not work as expected when an user provides correct credentials, but does not have the authorities to access a resource.
 
The io.vertx.ext.web.handler.impl.ChainAuthHandlerImpl class overrides the addAuthority and addAuthorities methods from the AuthHandlerImpl class to delegate to its chained handlers, but does not override the AuthHandlerImpl.authorize method, which uses the empty authorities field of the ChainAuthHandlerImpl class. Since the authorities field is always empty, the authorize method always succeeds and the user is allowed to access the resource.
Another issue with the ChainAuthHandlerImpl is that it does not support the use-case that one of its chained handlers requires one authority and another chained handler requires another authority. In my opinion, it doesn't make sense to set authorities on the ChainAuthHandlerImpl itself, but only on the individual auth handlers that are part of the chain. 

### Do you have a reproducer?

* https://github.com/cristic83/VertxBug

**Comment by pmlopes** [comment]
This is related to vertx web as chain auth does not perform or have authorities checks.

On vertx web the behavior when you add an authority it adds it to all registered auth providers.

What you’re observing in your image is that once you mix providers that support authorities and one which don’t we enter a state that authorities are not checked.

**Comment by pmlopes** [comment]
Chain auth now only does authentication, for authorization the new API addresses this issue.
