### ISSUE TITLE
OAuth2AuthProviderImpl always requires a client_secret

### ISSUE THREAD

**Issue by cristic83** [eclipse-vertx/vertx-auth#187]
### Version

* vert.x core: 3.5.0
* vert.x auth: 3.5.0
* vertx-auth-oauth2: 3.5.0

### Context

The OAuth2AuthProviderImpl always requires a client secret to be configured for the AUTH_CODE flow.
This is wrong, as in the case the OAuth2ClientOptions.setUseBasicAuthorizationHeader(false), e.g. because of using the private_key_jwt client authentication method (http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication private_key_jwt).

### Steps to reproduce

1. Create the AAuth2ClientOptions like below:

new OAuth2ClientOptions()
            .setClientID(environment.OAUTH2_CLIENT_ID)
            .setSite(environment.OAUTH2_SITE_URL)
            .setTokenPath(environment.OAUTH2_TOKEN_PATH)
            .setUserInfoPath(environment.OAUTH2_USER_INFO_PATH)
            .setUseBasicAuthorizationHeader(false);

2. Create an OAuth2Auth object like below:

OAuth2Auth.create(bootVertx.get(), OAuth2FlowType.AUTH_CODE, oAuth2ClientOptions);

3.  OAuth2AuthProviderImpl throws exception in line 54: "Configuration missing. You need to specify the client id, the client secret and the oauth2 server"

**Comment by pmlopes** [comment]
@cristic83 OIDC private_key_jwt was never considered as the code was initially only for OAuth2 and is being slowly being extended to support more OIDC features. I'll mark this issues as a new feature and if you're interested please review this code for more missing OIDC feature or help us with a pull request!

**Comment by pmlopes** [comment]
There has been a big refactoring on this code and I believe it has been addressed. If that's not the case please re-open.
