### ISSUE TITLE
Get user information failed with Facebook

### ISSUE THREAD

**Issue by julienBaleizao** [eclipse-vertx/vertx-auth#197]
### Version

* vert.x core: 3.5.1
* vert.x auth: 3.5.1

### Context

When I try to get the user information following this code:
`(OAuth2TokenImpl oAuth2Token).userInfo(...);`

The future failed with the message "Cannot handle Content-Type: text/javascript"
After looking at the Vertx code I see that you only handle the content type application/json, application/x-www-form-urlencoded or text/plain. The problem is that Facebook responds with content type text/javascript for the user information.
Do you have planned to fix this issue ? Is it the right way to retrieve user information ?

### Steps to reproduce

1. Use the FacebookAuth Vertx provider to authenticate an user
2. Once the Token is received call the method userInfo

**Comment by pmlopes** [comment]
@julienBaleizao could you debug and report the request + responses of this call? the content type `text/javascript` does seem incorrect as I assume it is a script and we will not run scripts. I expect a json payload.

Could you also try to reconfigure the provider with a version? e.g.:

```java
setUserInfoPath("https://graph.facebook.com/v2.12/me")
```

**Comment by julienBaleizao** [comment]
How can I activate the debug logging of HTTP request in Vertx ?
in the meantime I have added the header "Accept:application/json" to the facebook provider config to force the Fetch method of your OAuth2API class to use this header and then it is working. 
The facebook API responds with content type application/json instead of text/javascript.

**Comment by pmlopes** [comment]
@julienBaleizao that is good to know. It makes sense, that if you specify what you accept it replies with the correct value, I think that is the correct way to go.
