### ISSUE TITLE
Using jwtOptions in generateToken

### ISSUE THREAD

**Issue by sinnedh** [eclipse-vertx/vertx-auth#201]
### Version

* vert.x core: 3.5.1
* vert.x auth: 3.5.1

### Context

This issue is not a bug but rather a question/proposal.

In the 'JWTAuthProviderImpl' the `jwtOptions` parameter is only used in `authenticate` but not in `generateToken`. In the latter function, the `jwtOptions` need to be passed additionally: 

https://github.com/vert-x3/vertx-auth/blob/4079371267fb4b2ced3a47d405a37a85313f32f2/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWTAuthProviderImpl.java#L150

The corresponding interface `JWTAuthProviderImpl ` implements this function by simply creating new setting:

https://github.com/vert-x3/vertx-auth/blob/4079371267fb4b2ced3a47d405a37a85313f32f2/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/JWTAuth.java#L78

Is there any reason why one should not use the `jwtOptions` from the `JWTAuthProviderImpl` in `generateToken`?

**Comment by pmlopes** [comment]
Closing due to old API, please re-open if the current API is not enough.

**Comment by tiparega** [comment]
It already happens in 3.9.0:
https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/JWTAuth.java#L65

This could be ok in the interface as you don't have the options (but I think it shouldn't be a default implementation), but the implementation should override it
https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWTAuthProviderImpl.java
 
```
@Override
public String generateToken(JsonObject claims) {
    return generateToken(claims, jwtOptions);
}
```
