### ISSUE TITLE
Oauth 2 introspect and Cannot decode token

### ISSUE THREAD

**Issue by lecogiteur** [eclipse-vertx/vertx-auth#202]
Hi,

 In version 3.5.0, when I do an instropect. It's work no problem.

```scala
val accessToken = "MGre5434gDf"
oauth2.introspectTokenFuture(accessToken).onComplete {
        case Success(_) =>
          logger.info(s"The user token is authorized $accessToken")
          routingContext.next()
        case Failure(cause) =>
          logger.error(s"Not authorized for $accessToken", cause)
          routingContext.fail(401)
      }
```

After, I migrate to 3.5.1, I have this error in log

```
Cannot decode token: 
java.lang.RuntimeException: Not enough or too many segments
        at io.vertx.ext.jwt.JWT.decode(JWT.java:259)
        at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.decodeToken(OAuth2TokenImpl.java:102)
        at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.init(OAuth2TokenImpl.java:124)
        at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.<init>(OAuth2TokenImpl.java:83)
        at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.introspectToken(OAuth2AuthProviderImpl.java:222)
        at io.vertx.ext.auth.oauth2.OAuth2Auth.introspectToken(OAuth2Auth.java:167)
        at io.vertx.scala.ext.auth.oauth2.OAuth2Auth.introspectTokenFuture(OAuth2Auth.scala:166)

```

After investigation, it seems it's just a warning. The introspect works well. Is it necessary to log in warn level this stack trace? It is dangerous to mute log warn on class OAuth2TokenImpl ? Is it a normal process or I must configure something in order to not have this log?

**Comment by pmlopes** [comment]
indeed that's a log message that was being reported with the wrong level. I've fixed it on master, in order to reduce the noise you can configure your logger to ignore this class for now.

**Comment by lecogiteur** [comment]
Thanks

**Comment by johnoliver** [comment]
I believe this is an issue, inside [OAuth2TokenImpl](https://github.com/vert-x3/vertx-auth/blob/8850394fe8569f42f95b06c25a35267a36ae904c/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2TokenImpl.java#L129) it attempts to decode refresh tokens as if they are in the same format as access tokens. Which means that this exception is thrown and the refresh token is lost.

**Comment by pmlopes** [comment]
This has been fixed in master

**Comment by johnoliver** [comment]
Are you sure this was fixed? I still get these exceptions and looking at the code it still looks like OAuth2TokenImpl is trying to treat refresh_tokens as if they are a JWT
