### ISSUE TITLE
OAuth2TokenImpl: duplicate checks in token introspection 

### ISSUE THREAD

**Issue by nkuehn** [eclipse-vertx/vertx-auth#208]
### Version

* vert.x core: master
* vert.x auth: master

### Context

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2TokenImpl.java#L519  + ff 

Both the check for the `active` flag and the correct `client_id` are duplicate in the code.   The check for `client_id` is done slightly different, but functionally identical (looking into a local variable instead of getting the provider from scratch). 

### Do you have a reproducer?

Not a functionality bug, "just" housekeeping

### Steps to reproduce

n.a.

### Extra

n.a.

**Comment by pmlopes** [comment]
Thanks, there has been a large refactoring on this code and the check have been removed
