### ISSUE TITLE
OAuth2:  WARN level log message produced when expecting a JWT and given something else

### ISSUE THREAD

**Issue by sfitts** [eclipse-vertx/vertx-auth#210]
### Version

* vert.x core: 3.5.1
* vert.x auth: 3.5.1
* vert.x auth-oauth: 3.5.1

### Context

OAuth2 Token implementation is too verbose when unable to decode JWT.  In our use case we have both OAuth and internally managed tokens.  We start by seeing if the token is valid with the OAuth provider -- when this is one of our tokens it fails as expected, but it also produces a WARN level log message which clutters up our server logs.  Given that the API produces a failure so the caller can decide what to do the forced WARN message seems a bit verbose.  For now we're turning off that logger, but I'd really prefer not to.

### Steps to reproduce

Using the Keycloak OAuth provider attempt to validate an token that is not a JWT.  The result will be a failure (expected) with a WARN level log message (a bit too verbose).

### Extra

The issue is the log statement at line 105 in OAuth2TokenImpl.java

**Comment by pmlopes** [comment]
This has been fixed by: https://github.com/vert-x3/vertx-auth/pull/186
