### ISSUE TITLE
Vertx won't close successfully

### ISSUE THREAD

**Issue by ghost** [eclipse-vertx/vertx-auth#212]
### Version

* vert.x core: 3.5
* vert.x auth: 3.5

### Context

VertxContextPRNG doesn't mark the input future complete preventing call from CloseHooks.run from completion.

### Do you have a reproducer?

100% reproducible with steps below in any verticle that uses vertx-auth.

### Steps to reproduce

1. Launch any verticle with authentication enabled
2. Once running, hit ctrl+c to close the verticle
3. The process will be stuck for about two minutes (default after which the shutdown handler gives up)

### Extra

Relevant discussion thread from the forum -
https://groups.google.com/forum/#!topic/vertx/uma22CJbP6I

```
static VertxContextPRNG current(final Context context) {
  final String contextKey = "__vertx.VertxContextPRNG";
  // attempt to load a PRNG from the current context
  PRNG random = context.get(contextKey);

  if (random == null) {
    synchronized (context) {
      // attempt to reload to avoid double creation when we were
      // waiting for the lock
      random = context.get(contextKey);
      if (random == null) {
        // there was no PRNG in the context, create one
        random = new PRNG(context.owner());
        // need to make the random final
        final PRNG rand = random;
        // save to the context
        context.put(contextKey, rand);
        // add a close hook to shutdown the PRNG
        context.addCloseHook(v -> {
            rand.close();
            v.complete(); // Missing complete?
        });
      }
    }
  }

  return random;
}
```

**Comment by vietj** [comment]
@pmlopes your opinion ?

**Comment by pmlopes** [comment]
Perhaps the whole `PRNG` close should be removed. Basically what it does it stop a timer, so if vert.x is shutting down then it would be enough.

**Comment by vietj** [comment]
yep, if we can simplify it's great

**Comment by pmlopes** [comment]
@de1001 are you willing to make a PR removing all calls to `.addCloseHook`?
