### ISSUE TITLE
pom.xml: Element bnd is not allowed here

### ISSUE THREAD

**Issue by hsluoyz** [eclipse-vertx/vertx-auth#213]
I opened this project with latest ``IntelliJ IDEA 2018.1.3``. Then it alerts that all pom.xml files have the following error. And a lot of the symbols can't be resolved in .java files. I suspect it has something to do with the pom.xml error.

![qq 20180512133530](https://user-images.githubusercontent.com/3787410/39954008-651f88ce-55e9-11e8-8080-c2b3b69097ea.jpg)

**Comment by pmlopes** [comment]
This is not a bug, it is just that IDEA doesn't know how to handle this. If you run the maven from the command line you will see it will work, as well if you run it from the IDE using the maven menu bar.

**Comment by hsluoyz** [comment]
Thanks. I have reported this bug to IDEA. It can be tracked here: https://youtrack.jetbrains.com/issue/IDEA-192117

**Comment by pmlopes** [comment]
OSGi metadata has been removed and will not be supported on 4.0
