### ISSUE TITLE
Slow initialization of JWTAuth 

### ISSUE THREAD

**Issue by romnovi** [eclipse-vertx/vertx-auth#214]
Java works slow witn keystore, so JWTAuth.create(vertx, config) works slow (takes 1.2s in averange).
This issue heavily impacts perfomance of my unit-tests, because I deploy verticle with JWTAuth provider within before every test.

How about loading key store inside JWTAuthProviderImpl lazily?

**Comment by pmlopes** [comment]
Hi, I'm currently working on fully deprecate Java key stores in preference of openssl keys or the standard jwk. Perhaps you could look into using those as they are simpler and probably faster. However initialization code is run once, making it lazy would just move the issue somewhere else right? And perhaps would require locking mechanisms which would impact even worse the runtime performance, no?

**Comment by romnovi** [comment]
Ok, you persuaded me. Lazy init makes code more complicated. Could you give me a link "I'm currently working on fully deprecate Java key stores in preference of openssl keys or the standard jwk"

**Comment by pmlopes** [comment]
@mystdeim it started here: https://groups.google.com/forum/#!searchin/vertx-dev/jwt%7Csort:date/vertx-dev/SHXCvf-lass/wQCBCvhcAQAJ and some work has been done on the documentation part:

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jwt/src/main/asciidoc/index.adoc#using-rsa-keys
