### ISSUE TITLE
Groovy can not find method ShiroAuth.create(vertx, realm)

### ISSUE THREAD

**Issue by alober2** [eclipse-vertx/vertx-auth#22]
At the last of the documents (http://vert-x3.github.io/docs/vertx-auth-shiro/groovy/), I see I can use other Realm
class MyRealm extends AuthorizingRealm {
// other codes.
}
import io.vertx.groovy.ext.auth.shiro.ShiroAuth;
def realm = new MyRealm();
def provider = ShiroAuth.create(vertx, realm);

But When I create an Realm, I see there is no method ShiroAuth.create(vertx, realm);
groovy.lang.MissingMethodException: No signature of method: static io.vertx.groovy.ext.auth.shiro.ShiroAuth.create() is applicable for argument types: (io.vertx.groovy.core.Vertx, MyRealm)

**Comment by pmlopes** [comment]
This is a code gen issue `type org.apache.shiro.realm.Realm is not legal for use for a parameter in code generation` If you need more low level access you should use the Java API
