### ISSUE TITLE
Stormpath and vertx realm name disagree

### ISSUE THREAD

**Issue by gemmell** [eclipse-vertx/vertx-auth#23]
This is the next issue related to #21, see that ticket for the setup.

```
protected String getAccountHref(PrincipalCollection principals) {
       Collection c = principals.fromRealm(getName());
       //Based on the createPrincipals implementation above, the first one is the Account href:
       return (String) c.iterator().next();
 }
```

The `getName()` returns `com.stormpath.shiro.realm.ApplicationRealm_0` and then in `principals.fromRealm` it does:

```
public Collection fromRealm(String realmName) {
    if (realmPrincipals == null || realmPrincipals.isEmpty()) {
        return Collections.EMPTY_SET;
    }
    Set principals = realmPrincipals.get(realmName);
    if (principals == null || principals.isEmpty()) {
        principals = Collections.EMPTY_SET;
    }
    return Collections.unmodifiableSet(principals);
}
```

Where the `realmPrincipals` is a map with one entry: `vertx-auth-shiro`

So it seems stormpath is looking up by principal using it's name, but somehow only `vertx-auth-shiro` has been registered.

New key for playing around if you didn't sign up yourself:

```
apiKey.id = 1Z1YUWJA1YVHAICAOIU8P96VW
apiKey.secret = Bb9pCd07rzCOlQ7uLr1ZZF2Q/zKQi8dfGHerMJ8fBE8
```

**Comment by gemmell** [comment]
You can try to login with testname@test.com and pw 890fup*() and then do 

```
router.route().handler((RoutingContext context) -> {
    context.user().isAuthorised("role:0174870c-a06f-4337-900a-919b885f8a38+admins", (AsyncResult<Boolean> res) -> {
       if (res.succeeded()) {
          boolean hasPermission = res.result();
          if (hasPermission) {
             context.next();
          } else {
             context.response().setStatusCode(403).end("You do not have access to that group!");
          }
       } else {
          context.response().setStatusCode(403).end("Error asking if authorised");
       }
    });
 });
```

Note the group id is different to #21

**Comment by pmlopes** [comment]
I am trying to reproduce the issue with a unit test but i cannot login, could you provide some working credentials or check the commit above

**Comment by gemmell** [comment]
Hi Paulo if you want to keep it as a test case I suggest you create your own account at stormpath. I will be removing that key since it's my account which I may use for other things. It's really easy and free to sign up to stormpath.

You sign up
You create a user and give them a group
You create an API key
Done.

Hrrm. I will just do it all for you and make you an admin.

**Comment by gemmell** [comment]
Need your email addy.

**Comment by pmlopes** [comment]
The latest commit already have a account created by me, and it is fully functional see commit: https://github.com/vert-x3/vertx-auth/commit/8d8e7e32f536ec03a2957b94ed2bf19f15907345

It is just waiting for review and approval for merge into master.
