### ISSUE TITLE
In Auth2: logs more info, debug  messages to help debugging and understanding

### ISSUE THREAD

**Issue by BrunoVernay** [eclipse-vertx/vertx-auth#231]
### Version

* vert.x core: 3.5.2
* vert.x auth: 3.5.2

### Context

I try to use OAuth (OpenID Connect) to authenticate to Keycloak, but have a hard time figuring out what happen and what the API does.

It would be nice to know what is exchanged with the "OpenID Provider" or "Authorization Server", front and especially  **back** channel. 
Also know the content and state (expired?) of the tokens and the state of the flow (have Authorization Code, has Access Token, has IDToken ...)

### Do you have a reproducer?

* https://gitlab.com/BrunoVernay/oauth-vertx-kotlin

**Comment by BrunoVernay** [comment]
Also some related pieces are in https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java

**Comment by pmlopes** [comment]
Code has been merged.
