### ISSUE TITLE
Support for KeyCloak Multi Tenancy with KeycloakConfigResolver

### ISSUE THREAD

**Issue by adpande** [eclipse-vertx/vertx-auth#238]
### Version

* vert.x core: 3.5.3
* vert.x auth: 3.5.3

### Context

We are implementing multi-tenancy using Keycloak where each tenant will have its own realm. The tenant and its corresponding Keycloak realm will be identified using URL subdomain. Currently vertx Keycloak support authenticating against one single realm only. 

It would be really good if we can give some handler just like KeycloakConfigResolver (https://www.keycloak.org/docs/latest/securing_apps/index.html#_multi_tenancy) to dynamically select the Keycloak relalm to use.

### Extra

* https://www.keycloak.org/docs/latest/securing_apps/index.html#_multi_tenancy

**Comment by pmlopes** [comment]
I think you're looking for:

https://vertx.io/docs/vertx-web/java/#_virtualhost_handler

You create a OAuth2Handler for each tenant, the for each tenant, say `tenant1, ... tenantN`:

```java
router.route().handler(
  VirtualHostHandler.create("tenant1.yourapp.com", OAuth2Handler.create(tenant1Config));
...
router.route().handler(
  VirtualHostHandler.create("tenantN.yourapp.com", OAuth2Handler.create(tenantNConfig));
```

**Comment by adpande** [comment]
Hi @pmlopes, I think this will not work as tenents register by themselves and I do not know at start time which tenants will come.

**Comment by pmlopes** [comment]
In that case you need to write an handler like the code you shown:

```java
ctx -> {
  if (ctx.request().path().startsWith("alternative")) {
    oauth2handlerForAlternative.handle(ctx);
  } else {
    oauth2handlerFallback.handle(ctx);
  }
}
```

To make things more robust, you probably need to have a local map `sharedData()` that maps your tenants to the oauth2 handlers, so they are cached and some routes/config to add/remove/reconfigure the local map.

**Comment by adpande** [comment]
Ohh.. This is awesome! I will try this out! Thanks a lot!

**Comment by adpande** [comment]
Hi @pmlopes, 
I tried this and it works! The only issue I am facing is: How to get user object in call back? 
In the callback route it is giving me the code (I think JWT) but how to decode and get User object and principle from it?
`
state: /ui/get
session_state: 93859cab-9664-4a29-a27d-fdb13a8dfebd
code: eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..5z9qteIogtGKSJ_V7SeAwg.Y-iKTRX_7JBRlxhht3Z-cFmgAsxGXe-NOKsBGpqeNJJRtS6GDqN_4QdJ2t27EkwQ0J5R2Q5InrNxrzx5pbL8pjhNV--kI2e1-fylZ01wKfwp74SuT9s4Rlr4Txb4cmRdqQFfaUWl1suTz_e90mxFyTaa8v9gXNJDJjfhGw8Knz4xd5rzRxfJsKUNHqKzgr2LhzSftcjAPovLBJLDFkR5GU-fm6TzAkmdDbvf_5b4yN_yr7PX1d2Ih0nCZLrtZEwF.S5zVcZo-nYOH2xNOBwMz5g
`

I have also tried to setup handler like this:
```java    
                OAuth2Auth oauth2 = KeycloakAuth.create(vertx, OAuth2FlowType.AUTH_CODE, new JsonObject(a));
                oauth2.authenticate(tokenConfig, (AsyncResult<User> event) -> {
                    System.out.println("Event User:"+event.result().principal());
                });
                OAuth2AuthHandler oauth2Handler = OAuth2AuthHandler.create(
                        oauth2
                );

                oauth2Handler.setupCallback(callback);
                oauth2Handler.handle(routingContext);
```
But it always returns null for user Object.

Thanks & Regards,
Abhishek

**Comment by adpande** [comment]
I have now removed the custom callback handler that I have written. I am now just passing the route to the callback like: 
```
oauth2Handler.setupCallback(router.get("/callback"));
```
It is working but, I have still not able to figure out how will I get the user and principle objects.

Thanks!

**Comment by adpande** [comment]
This issue is solved. Actually I was making the mistake of writing own callback. I am able to get the user from ctx now. Thanks @pmlopes for the help!
