### ISSUE TITLE
Expose JDBCUser constructor outside of package

### ISSUE THREAD

**Issue by rgmz** [eclipse-vertx/vertx-auth#239]
I would like to allow authentication via both JDBC auth and OpenID Connect (OAuth2 auth), but use JDBC auth for authorization regardless of the initial auth provider. 

i.e Authenticate via OpenID Connect -> get username -> create JDBC session from username

Presently this is not possible as [JDBCUser is package-private](https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jdbc/src/main/java/io/vertx/ext/auth/jdbc/impl/JDBCUser.java#L45).

Are there any issues (security or otherwise) that would make this flow impractical?

**Comment by tsegismont** [comment]
How about building your own `AuthProvider`? You could inspire from [chained auth](https://github.com/vert-x3/vertx-auth/commit/a3eba6a42fe132cc9677c2529c7d603a83d7f52f)

By the way @pmlopes , it seems chained auth is not documented. Is there an issue for tracking this?

**Comment by rgmz** [comment]
Interesting — I was not aware of ChainedAuth, but I will look into that, thanks!

(Keeping this open so pmlopes can respond to your question.)
