### ISSUE TITLE
please share samples using the vertx-auth

### ISSUE THREAD

**Issue by alanma** [eclipse-vertx/vertx-auth#24]
It would be great to add examples to use different auth module in the project. Or please share examples in documentation if possible.

Thanks.

**Comment by pmlopes** [comment]
Actually there are already a couple of examples, see here:
- https://github.com/vert-x3/vertx-examples/tree/master/web-examples/src/main/java/io/vertx/example/web/auth
- https://github.com/vert-x3/vertx-examples/tree/master/web-examples/src/main/java/io/vertx/example/web/authjdbc
- https://github.com/vert-x3/vertx-examples/tree/master/web-examples/src/main/java/io/vertx/example/web/jwt

Examples for all components are added to that central repository as a easy to find location
