### ISSUE TITLE
OAuth2AuthHandler does not introspect a parsed token

### ISSUE THREAD

**Issue by MightyEagle82** [eclipse-vertx/vertx-auth#241]
### Version

* vert.x core: 3.5.3
* vert.x auth: 3.5.3

### Context

I see that OAuth2AuthHandler does not analyze any information in a decoded token (for example, expiration time). So it allows access to protected resources with any valid token.

### Steps to reproduce

1. Set up OAuth2AuthHandler with correct configuration.
2. Make a request to a protected resource with a valid but expired token.

Result: The request is not rejected.

**Comment by steven-aerts** [comment]
We are running into this one too.
Can somebody confirm it is expected behaviour that jwt token expiration is not validated?

We are confused about this as other jwt related auth handlers seem to do so: https://vertx.io/docs/vertx-auth-jwt/java/#_authenticating_authn

Thanks,

   Steven
