### ISSUE TITLE
Keycloak bearer-only access type: OAuth2AuthHandlerImpl throws 500 instead of 401 when Authorization header is absent

### ISSUE THREAD

**Issue by vanhaegendorenb** [eclipse-vertx/vertx-auth#242]
### Version

* vert.x core: 3.5.3
* vert.x auth: 3.5.3

### Context

Consider a client that wants to access a protected resource offered by a service that implements the bearer-only access type. Keycloak (https://www.keycloak.org/docs/3.1/authorization_services/topics/enforcer/keycloak-enforcement-bearer.html) is used as an auth provider that offers the client an access token after successful authentication, the resource server receives a HTTP request with an Authorization header containing the bearer token which has to be verified successfully before the resource can be provided. 
The resource server uses the KeycloakAuth provider to verify the bearer token, an OAuth2AuthHandler instance is installed as follows:

vertx = Vertx.vertx(options);
Router router = Router.router(vertx);
OAuth2Auth authProvider = KeycloakAuth.create(vertx, authConfig);
...
Future<Void> f = Future.future();
authProvider.loadJWK(f);
...
OAuth2AuthHandler oauth2 = OAuth2AuthHandler.create(authProvider); [1]
router.route().handler(oauth2);
... >> resource server installs additional handlers
... >> resource server is ready to handle requests

The OAuth2AuthHandlerImpl::setupCallback method isn't applicable for this use case, only the bearer token received in the Authorization header should be verified, no need to contact Keycloak, the resource service has the key set and configuration to verify the bearer token. 

The issue now is that when the OAuth2AuthImpl::parseCredentials method is called by the vert.x auth framework to decode and verify the bearer token, and a request is received without Authorization header, a HTTP 500 status code is returned to the client instead of a 401.

Cause: If OAuth2AuthHandlerImpl::setupCallback isn't called OAuth2AuthHandlerImpl.callback == null, if no Authorization header is present in the HTTP request token == null. as a result this method will call handler.handle(Future.failedFuture("callback route is not configured.")); which shouldn't happen in a bearer-only access type scenario.

### Steps to reproduce

1. Start-up vert.x web server as described above
2. Send HTTP client request without Authorization header
3. Server returns a HTTP 500 status code instead of 401

### Extra
Workaround: install following handler replacing [1] resulting in proper error handling for the bearer-only access type case. 

        oauth2 = new OAuth2AuthHandlerImpl(authProvider, null) {
            public void parseCredentials(RoutingContext context, Handler<AsyncResult<JsonObject>> handler) {
                this.parseAuthorization(context, false, (parseAuthorization) -> {
                    if (parseAuthorization.failed()) {
                        handler.handle(Future.failedFuture(parseAuthorization.cause()));
                    } else {
                        String token = parseAuthorization.result();
                        if (token == null) {
                            throw new IllegalStateException("bearer-only access type: token is null");
                        } else {
                            ((OAuth2Auth) this.authProvider).decodeToken(token, (decodeToken) -> {
                                if (decodeToken.failed()) {
                                    handler.handle(Future.failedFuture(new HttpStatusException(
                                            HttpURLConnection.HTTP_UNAUTHORIZED, decodeToken.cause().getMessage())));
                                } else {
                                    context.setUser(decodeToken.result());
                                    handler.handle(Future.succeededFuture());
                                }
                            });
                        }
                    }
                });
            }

**Comment by pmlopes** [comment]
@vanhaegendorenb A fix is proposed in the `vertx-web` repo. Tests show that when there are valid tokens they get handled by the JWT config of the oauth2 server on any other case, it always returns 401 as expected. Would you mind to give it a review?

**Comment by vanhaegendorenb** [comment]
Sure @pmlopes PR looks fine, one remark though regarding the token == null error handling for bearer-only case: vertx-web should return a HTTP 401.
