### ISSUE TITLE
KeycloakHelper parseToken function does not decode properly

### ISSUE THREAD

**Issue by castx1981** [eclipse-vertx/vertx-auth#244]
Here is the code snippet:
`String decoded = new String(Base64.getDecoder().decode(parts[1]), "UTF-8");`

it should be Base64.getUrlDecoder()

**Comment by pmlopes** [comment]
Fixed by https://github.com/vert-x3/vertx-auth/commit/5bf60d8da3d5ec119f835d175591f4af6eb1a537
