### ISSUE TITLE
HashStrategy as common utils

### ISSUE THREAD

**Issue by rogelio-o** [eclipse-vertx/vertx-auth#251]
Currently, the hash strategies are implemented as JDBCHashStrategy in the vertx-auth-jdbc artifact. I'd be helpful move this to artifact vertx-auth-common as HashStrategy because it's also used in vertx-auth-mongo (where it has been copied) and it could be used in vertx-auth-jwt + custom user adding (or other combination which implies user adding).

**Comment by pmlopes** [comment]
A new p-c-h compliant strategy is implemented on `common` which fixes this issue.
