### ISSUE TITLE
[OAuth2] Recently added logging is too verbose

### ISSUE THREAD

**Issue by sfitts** [eclipse-vertx/vertx-auth#253]
### Version

* vert.x core: 3.6.2
* vert.x auth oauth2: 3.6.2

### Context

The logging produced by the OAuth2 code is extremely verbose (info level logs every response created and every URI accessed for example).  It appears that most of this was added in https://github.com/vert-x3/vertx-auth/commit/05735addae6fc4f0a9b7445eba88f3b16af0ab5c (for context).

I know this is subjective, but IMO just about everything is one level too high (the info logging should be debug and the debug logging should be trace).  This is in comparison to the logging done by Vert.x core and by other Vert.x libraries (we use several).

**Comment by pmlopes** [comment]
@sfitts I think we can lower it as you suggested. Can you make a pull request for it?

**Comment by sfitts** [comment]
I'll see if I can put one together later this week.

**Comment by pmlopes** [comment]
Was fixed on 3.6.3
