### ISSUE TITLE
io.vertx.ext.auth.jdbc.JDBCAuth use reserved word in postgres

### ISSUE THREAD

**Issue by neuneuraxis** [eclipse-vertx/vertx-auth#254]
I use io.vertx.ext.auth.jdbc.JDBCAuth with a database postgres (v10) . The default query for authenticate is 
https://github.com/vert-x3/vertx-auth/blob/a79586d8ffe17ff6ca180ae32fa910f1034d8153/vertx-auth-jdbc/src/main/java/io/vertx/ext/auth/jdbc/JDBCAuth.java#L43
But in postgres «user» is a reserved word and the query end in error 
`org.postgresql.util.PSQLException: ERREUR: la colonne « password » n'existe pas`

My solution is change name of table and override the query.

links :
[https://stackoverflow.com/questions/22256124/cannot-create-a-database-table-named-user-in-postgresql](https://stackoverflow.com/questions/22256124/cannot-create-a-database-table-named-user-in-postgresql)
[https://www.postgresql.org/docs/10/sql-keywords-appendix.html](https://www.postgresql.org/docs/10/sql-keywords-appendix.html)

Best regards

**Comment by pmlopes** [comment]
We could quote the table name making it not a reserved word no?

**Comment by tsegismont** [comment]
@pmlopes we could, but it would still be a pita for users querying from the database shell.

From my perspective, it would be fine to change the default user table name as most users are probably already overriding the default query (for the reason described above).

**Comment by pmlopes** [comment]
Fix for the new SQL client https://github.com/vert-x3/vertx-auth/commit/02085c4bc85bbb72aefd5dab5f01880fdc411dfa
For the old JDBC use the override settings as it would break for non postgres users.
