### ISSUE TITLE
io.reactivex.ext.auth.VertxContextPRNG does not have nextBytes()

### ISSUE THREAD

**Issue by paninics** [eclipse-vertx/vertx-auth#262]
### Version

* vert.x core: 3.6.3
* vert.x auth: 3.6.3

### Context
The interface `io.vertx.ext.auth.VertxContextPRNG` has `nextBytes()` but it's omitted in the auto generated `reactivex` package since this method is tagged to be ignored. However, if one looks at `io.reactivex.ext.auth.VertxContextPRNG.nextString()` method, it eventually calls `io.vertx.ext.auth.VertxContextPRNG.nextBytes()`. Hence not sure the motivation to drop this method. By not having the `nextBytes()` in the `reactivex` package, one is forced to call `nextString()` and then decode the string to bytes - an unnecessary step if we need the raw bytes to begin with.

**Comment by pmlopes** [comment]
This was due to a limitation on codegen, perhaps with the new code (on codegen) this will be valid or we can tag the method to be allowed using the new annotation.

**Comment by pmlopes** [comment]
This issue has been fixed on codegen.
