### ISSUE TITLE
Add possibility to load cert from pem directly

### ISSUE THREAD

**Issue by pendula95** [eclipse-vertx/vertx-auth#266]
### Version

* vert.x core: 3.6.3
* vert.x auth: 3.6.3

### Context

Add possibility to load cert public/private via pem file located in class path instead of keeping it in source code. 

### Idea behind:

We wanted to add possibility of dynamic creation and import of cert to JWT Auth. As with current options it is only possible to keep the public and private key in source code. We want to avoid this. The workaround was to load it from config. To achieve this automatic we would need to create public and private cert with openssl and than extract the keys from theme (you need to remove "-----BEGIN RSA PRIVATE KEY-----"... and put them in config file. This was not friedly to use so we went with generating a keystore. Keystore was smelly to as Classes are deprecated and when generating the keystore with default command was generated a warning  

`The JCEKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format using "keytool -importkeystore -srckeystore idbox.jceks -destkeystore idbox.jceks -deststoretype pkcs12".`

After trying to use  -storetype pkcs12 vertx was not able to open the keystore.

So these 2 problems are already too smelly. 

Is it possible to add feature to load certs from pem files instead of keeping them in source code or config.

**Comment by pmlopes** [comment]
Fixed on 0310d7e43aaa310714bee7c4695e9d9f5be285e7

PEMs still need to be passed to a `PubSecKeyOptions` object because some extra metadata is required, but the file can just be loaded as is.
