### ISSUE TITLE
OAuth2UserImpl.java : check if token is expired in seconds, not milliseconds

### ISSUE THREAD

**Issue by javathought** [eclipse-vertx/vertx-auth#269]
### Version

* vert.x core: 3.6.3
* vert.x auth: 3.6.3

### Context

I encountered a problem with Strava tokens : 
expires_at is in seconds and OAuth2UserImpl::expired function compares it with current time in milliseconds

```java
    long now = System.currentTimeMillis();
    // expires_at is a computed field always in millis
    if (principal.containsKey("expires_at") && principal.getLong("expires_at", 0L) < now) {
      return true;
    }
```

### Do you have a reproducer?
No

### Extra

In Strava documentation, expires_at is specified in seconds

http://developers.strava.com/docs/authentication/#token-exchange
> "A refresh token, access token, and access token expiration date will be issued upon successful authentication. The expires_at field contains the number of seconds since the Epoch when the provided access token will expire."

In RFC, expires_in is specified to be in seconds too : https://tools.ietf.org/html/rfc6749#section-4.2.2
> expires_in
         RECOMMENDED.  The lifetime in seconds of the access token.  For
         example, the value "3600" denotes that the access token will
         expire in one hour from the time the response was generated.
         If omitted, the authorization server SHOULD provide the
         expiration time via other means or document the default value.

Link to Vert.X code : 
https://github.com/vert-x3/vertx-auth/blob/753e4dcc4b56df044cd20c2c5961652546ef0e62/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2UserImpl.java#L246

**Comment by pmlopes** [comment]
`expires_at` is not a spec'ed field and is used internally, so it seems that `strava` diverged from the spec. In order to make this easier we could handle the field seconds too.

**Comment by pmlopes** [comment]
strava also returns the official spec `expires_in` which is now properly handled. We don't rely on the `expires_at` field anymore so this field will not affect any checks anymore.
