### ISSUE TITLE
I want to use my own AuthenticationToken

### ISSUE THREAD

**Issue by Anillc** [eclipse-vertx/vertx-auth#271]
### Version

* vert.x core:3.6.3
* vert.x auth:shiro auth+jwt auth

### Context

I want to use my own AuthenticationToken for JWT auth logining

**Comment by pmlopes** [comment]
I don't understand the issue could you explain it in more detail?

**Comment by Anillc** [comment]
I need to use two ways to authenticate my account. First, I will call the restful API with username and password and the API returns a jwt token. Then I will request other APIs with tokens. I derived Realm and AuthenticationToken, and I want to check the token in my own Realm. But the shiro auth of vertx only supports UsernameAndPasswordToken.

**Comment by pmlopes** [comment]
authn and authz are now decoupled. Shiro is deprecated.
