### ISSUE TITLE
Google OAuth2 implementation does not have logout path

### ISSUE THREAD

**Issue by lukehutch** [eclipse-vertx/vertx-auth#273]
### Version

* vert.x core: 4.0-SNAPSHOT
* vert.x auth: 4.0-SNAPSHOT

### Context

Logout fails with Google OAuth2 implementation, because `OAuth2ClientOptions::getLogoutPath` returns null, which causes a failure at `OAuth2TokenImpl` line 286 (in the `getApi().fetch()` call, within the `logout` method).

The logout URL is described in this post: https://stackoverflow.com/a/23245957/3950982

(the idea is to revoke the `access_token`)

**Comment by pmlopes** [comment]
Oauth2 now implements: Revoke an obtained access token. More info <a href="https://tools.ietf.org/html/rfc7009">https://tools.ietf.org/html/rfc7009</a>.

```java
oauth2.revoke(userObject)
  .onComplete(...)
```

This is automatically discovered using openid on the google provider.
