### ISSUE TITLE
OpenIDConnectAuth discover and flow OAuth2FlowType.AUTH_JWT are not compatible

### ISSUE THREAD

**Issue by frx08** [eclipse-vertx/vertx-auth#275]
### Version

* vert.x core: 3.6.3
* vert.x auth: 3.6.3

### Context

OpenIDConnectAuth discover and flow OAuth2FlowType.AUTH_JWT are not compatible
because OpenIDConnectAuth .discover() lazy load the jwk configuration with .loadJWK()
while AuthJWTImpl requires pubSecKeys configured in constructor, I cannot add a placeholder configuration in the pubSecKeys because than the validation for the JWT tokens is failing

### Steps to reproduce

OpenIDConnectAuth.discover(vertx, new OAuth2ClientOptions()
  .setSite("XXX")
  .setFlow(OAuth2FlowType.AUTH_JWT));

**Comment by pmlopes** [comment]
JWT flow is a Google specific flow for app to app communication. This is not compatible with OpenID Connect.

This flow is described here:

https://developers.google.com/identity/protocols/OAuth2ServiceAccount

**Comment by frx08** [comment]
Thank you @pmlopes in my scenario I'm integrating ADFS / AZURE where it is possible to implement a JWT FLOW and it is also OpenID 'compliant' (probably it is a edge case)
https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-on-behalf-of-flow

**Comment by pmlopes** [comment]
@frx08 I didn't know about this Azure feature. So it seems that for azure this is also possible but it has a couple of extra requirements: `requested_token_use`, `scope` and even use a different host `https://graph.windows.net`. I'll mark this issue as an improvement as we might be able to get this to work too...
