### ISSUE TITLE
Why Mongo Auth not to separate User-Role collection and Role-Permission collection?

### ISSUE THREAD

**Issue by UkonnRa** [eclipse-vertx/vertx-auth#276]
### Version

* vert.x core: 3.6.3
* vert.x auth: 3.6.3

### Context

In Mongo-Auth, you can only set *ONE* collection which should contain user, role and permission field together. And in your test examples, the {user, role} and {role, premission} are combine together. I wonder is this an ideal design? Why can't I separate {user, role} and {role, premission} to two separate collections, just like JDBC's design? JDBC Auth can set `setPermissionsQuery` and `setRolesQuery`, while Mongo have not such settings...

**Comment by saumiktewari** [comment]
@CasterKKK 
I too have the same problem. In fact, [here](https://vertx.io/docs/vertx-auth-mongo/kotlin/) their documentation says

"Although Vert.x auth itself does not mandate any specific model of permissions (they are just opaque strings), this implementation assumes a familiar user/role/permission model, where a user can have zero or more roles and a role can have zero or more permissions."

But their implementation puts {user, roles and permissions} in the same collection tightly coupling user with permission. This way roles become useless.

**Comment by UkonnRa** [comment]
@saumiktewari Finally, I just implement `AbstractUser` and `AuthProvider` by myself, it's not difficult.

**Comment by pmlopes** [comment]
Fixed by #353
