### ISSUE TITLE
Keycloak 4.8.3 Open ID Connect does not work because refresh token decoding fail

### ISSUE THREAD

**Issue by vinscom** [eclipse-vertx/vertx-auth#277]
### Version

* vert.x auth 3.6.3:

### Context

I am using Keycloak 4.8.3. As part of integration with Keycloak using Auth Code flow. I get error "Algorithm not supported" from JWT.java [Line 280] while decoding "refresh_token" Auth2UserImpl [Line 72]. This is happening because in Keycloak (https://issues.jboss.org/browse/KEYCLOAK-4622), refresh_token specifically uses HS256 and where as access_token and id_token uses RS256. Before this I was using 3.4.3 and everything was working fine. 

### Do you have a reproducer?

Current integration with Keycloak won't work (I have tired Open ID Connect integration). Because, now keycloak encodes refresh_token as HS256. And as per keycloak, since, refresh token is only used by keycloak, it should be handled as opeque string. In current implementation, code always tries to decode refresh token.  
Not sure, what is the use of decoded refresh token. As during refresh of token, only opaque string is used.

**Comment by pmlopes** [comment]
The best is to disable parsing of the refresh token.

**Comment by pmlopes** [comment]
Fixed by: https://github.com/vert-x3/vertx-auth/pull/278
