### ISSUE TITLE
Support path variables in AuthHandler.addAuthority()

### ISSUE THREAD

**Issue by stephanebastian** [eclipse-vertx/vertx-auth#281]
In vertx, to secure a route you can currently write something like this:

`
// check that the user has the permission to delete product
router.delete("/products/:productId")
.handler(RedirectAuthHandler.create(authProvider).addAuthority("product:delete"))
`

However, sometimes I really want to check that the user has the permission to delete a specific productId and would like to write something like this:

`
// check that the user has the permission to delete product
router.delete("/products/:productId")
.handler(RedirectAuthHandler.create(authProvider).addAuthority("product:delete:{productId}"))
`
In this case, if the route is '/products/pid123' I would expect Vertx to check for the following authority: "product:delete:pid123"

@pmlopes What do you think ? 
I can send you a PR this week if you feel it's a nice feature to add

**Comment by pmlopes** [comment]
This has been addressed on the new authorization API
