### ISSUE TITLE
Refreshing AuthProvider

### ISSUE THREAD

**Issue by chris-brace** [eclipse-vertx/vertx-auth#282]
### Version

* vert.x core: 3.7.1
* vert.x auth: 3.7.1

---

I use a JWKS provided by Auth0 to authenticate REST endpoints. The well-known keys are downloaded at runtime. I've been digging around the vertx-auth docs and the code and I can't figure out how I would re-download the keys after a time interval in case they have changed.

If this isn't possible that would be nice to know, though Auth0's server examples all seem to have the key refreshing itself after some amount of time on the order of 5 minutes.

**Comment by mohamnag** [comment]
I'm also interested in knowing a solution for this. Recently I used Spring Security version of Auth0 lib which just needs audience and issuer to be configured and everything else was managed by the lib. I would like to see an equivalent lib here too. In most of the cases I'm not going to issue tokens from same API and just want to verify signatures and don't want to include any keys in each of services. 
If provider (here i.e. Auth0) has a well-known way of getting and refreshing JWKs from a URL, that should be possible to use too, including the periodic check of keys and reloading them.

**Comment by pmlopes** [comment]
Oauth2 auth can reload keys with jwkSet call. JWT auth will follow with reload of config soon.

**Comment by arnauddegiuli** [comment]
Top!
Thanks a lot.

Arnaud

Le jeu. 5 déc. 2019 à 13:32, Paulo Lopes <notifications@github.com> a
écrit :

**Comment by chris-brace** [comment]
@pmlopes thank you for the update! i'd forgotten about this issue! :)

**Comment by mohamnag** [comment]
it would be very nice if by closing each ticket it is mentioned as of which version and how (a link to new/updated docs) this has been fixed ;)

**Comment by pmlopes** [comment]
this has been merged on master a while ago. JWK reload are already on 3.9.1 and will be soon on 4.0.0 milestone 5
