### ISSUE TITLE
OAUTH 2.0 token parsing with Client flow

### ISSUE THREAD

**Issue by sklakegg** [eclipse-vertx/vertx-auth#288]
### Version

* vert.x core: 3.7.1
* vert.x auth: 3.7.1

Parsing AT from github using OAUTH 2.0 CLIENT flow. The result comes as {"result":{"access_token": ....

However, seems like the parsing methods used in the library expect the result json without the result field so it would look like this: {"access_token"

### Do you have a reproducer?

To get around I have to create a new OAuth2TokenImpl after the init parsing fails.
AccessToken asd = new OAuth2TokenImpl(oauth2, res.result().principal().getJsonObject("result"));

**Comment by pmlopes** [comment]
This code has been refactoring in 4.0.0 and should be fixed.
