### ISSUE TITLE
Azure B2C requires a parameter for the ".well-known" discovery address

### ISSUE THREAD

**Issue by smil2k** [eclipse-vertx/vertx-auth#293]
### Version

* vert.x core: latest
* vert.x auth: latest

### Context

I'm using AzureADAuth.discover to load the JWKs array.

Azure AD B2C requires the "profile" also as a query parameter like this:
https://bla.b2clogin.com/bla.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_Simple

Unfortunately the configuration "site"
will get appended with ".well-known/openid-configuration" unconditionally, therefore it is not possible to use OAuth2 discovery with Azure AD B2C.

As a hack, I've added "&x=" to the end of the above line, this way the added suffix is handled as a parameter and the service returns the right profile.

It would be good to either check for ".well-known" before appending the path or make it possible to append query parameters from the config.

**Comment by pmlopes** [comment]
@smil2k is this a duplicate of https://github.com/vert-x3/vertx-auth/issues/270 ?

**Comment by smil2k** [comment]
Hi,

No. This bug is about the burned in ".wll-known/openid-configuration" suffix after the site property.
The other one is about the contents of the discovery document. (namely the tenant attribute)

**Comment by pmlopes** [comment]
Ok, can you point me to the documentation of this feature on azure docs? I'm not sure I totally understand the problem.

**Comment by smil2k** [comment]
Azure AD B2C (https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oidc).
On the portal it returns the OIDC address like this: https://bla.b2clogin.com/bla.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_Simple

In this format the query parameter is compulsory.

It seems tough, that there is another format, where the profile is composed into the path, this can be used with the current code:
site=https://bla.b2clogin.com/bla.onmicrosoft.com/B2C_1_Simple/v2.0/

Therefore I'll close this ticket.
