### ISSUE TITLE
The wrong SQL script to create role/permissions table in jdbc-auth

### ISSUE THREAD

**Issue by Gogomoe** [eclipse-vertx/vertx-auth#312]
I noticed that the primary key of `roles_perms` is `(role)` but not `(role, perm)` in [sql file](https://github.com/vert-x3/vertx-auth/blob/4.0.0-milestone3/vertx-auth-jdbc/src/main/resources/jdbc-auth-ddl.sql) and [docs](https://vertx.io/docs/vertx-auth-jdbc/java/#_jdbc_auth_provider_implementation).
``` sql
CREATE TABLE `roles_perms` (
  `role` VARCHAR(255) NOT NULL,
  `perm` VARCHAR(255) NOT NULL
);
ALTER TABLE roles_perms ADD CONSTRAINT `pk_roles_perms` PRIMARY KEY (role);
```

A role can only correspond to one permission according the table structure. That would make it impossible to implement permission-role model.

Is that a mistake?

**Comment by pmlopes** [comment]
@stephanebastian could you verify this?

**Comment by francoisprunier** [comment]
Hi @pmlopes,

I'm going to look into it.

**Comment by francoisprunier** [comment]
@pmlopes I've created this PR: https://github.com/vert-x3/vertx-auth/pull/348
