### ISSUE TITLE
Investigate whether or not it's possible to replace all custom User implementations (JWTUser, JDBCUSer, etc.) with one UserImpl

### ISSUE THREAD

**Issue by stephanebastian** [eclipse-vertx/vertx-auth#314]
This would greatly simplify the existing code base. 
Also, as a bonus we could probably make User a DataObject.
@pmlopes WDYT ?

The idea is to provide only one user that can be used by all Auth projects.

In term of API we should deprecate:

- public User clearCache();
==> equivalent to user.authorizations.clear();
- public User isAuthorized(String authority, Handler<AsyncResult<Boolean>> resultHandler);
resultHandler) {
- public void setAuthProvider(AuthProvider authProvider)

We should probably add a method on the RoutingContext to verify authorization:
- public RoutingContext verifyAuthorization(Authorization authorization, Handler<AsyncResult<Boolean>>

**Comment by pmlopes** [comment]
Fixed by #343
