### ISSUE TITLE
AbstractOAuth2Flow: Add possibility to supress putting client_id and client_secret to form

### ISSUE THREAD

**Issue by kthoms** [eclipse-vertx/vertx-auth#319]
### Version

* vert.x core: 3.8.3
* vert.x auth: 3.8.3

### Context

We tried to authenticate with OAuth via Client Credentials against [Billwerk](https://billwerk.com/). We got a BAD_REQUEST and found out that Billwerk does not accept the request when either `client_id` or `client_secret` are part of the form body.

The  [Billwerk authentication documentation](https://developer.billwerk.io/Docs/ApiIntroduction#authentication) mentions:

> Please note that client_id MUST NOT be specified in the request body because it's already contained in the Basic authorization header. 

I did not see how to supress this, so I guess there should an option in `OAuth2ClientOptions` which is evaluated in `AbstractOAuth2Flow#getToken()`.

### Steps to reproduce

- Use the code from [Client Credentials Flow](https://vertx.io/docs/vertx-auth-oauth2/java/#_client_credentials_flow)
- Use site `https://sandbox.billwerk.com`

Once the both form properties are removed Billwerk sends a token.

**Comment by kthoms** [comment]
According to the [RFC-6749, 4.4.2](https://tools.ietf.org/html/rfc6749#section-4.4.2) the body only contains `grant_type` and optionally `scope`. No word about additional values.

**Comment by aaronanderson** [comment]
I am using the Quarkus OIDC extension based on Vert.x and I am receiving a similar error with Okta as the OIDC IDP:

`{"error":"invalid_request","error_description":"Cannot supply multiple client credentials. Use one of the following: credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body."}`

This error was encountered with the authorization_code grant type.

**Comment by kthoms** [comment]
I have worked around by copying `io.vertx.ext.auth.oauth2.impl.flow.AbstractOAuth2Flow` and `io.vertx.ext.auth.oauth2.impl.flow.ClientImpl` into one custom class and avoid the form enrichment, and subclass `OAuth2AuthProviderImpl` to create the custom flow. Feels ugly, but works.

**Comment by pmlopes** [comment]
@kthoms we would like to have a standards/spec compliant client, as you noticed we are not compliant with the RFC, I think we should mark this as a bug.

So from the link you pasted, in client credentials grant, we should not send the extra form

**Comment by sberyozkin** [comment]
@pmlopes Hi Paulo, and please backmerge it to 3.8.x :-)

**Comment by pmlopes** [comment]
I will once it's fixed ;)

**Comment by sberyozkin** [comment]
@pmlopes Can you please try to find few mins to fix it ? We can't really interoperate with any OIDC IDP but Keycloak at the moment, thanks

**Comment by pmlopes** [comment]
@sberyozkin I've been already working on this, please review: https://github.com/vert-x3/vertx-auth/pull/336

**Comment by pmlopes** [comment]
Fixed by #343

**Comment by nikhil-cdac** [comment]
I faced the BAD_REQUEST error with okta, and cannot upgrade to v4.0.0. I workarounded the error by setting useBasicAuthorizationHeader to false in OAuth2ClientOptions. this way client_id and client_secret are passed only in body and not in auth header.
