### ISSUE TITLE
 Add a new provider to authenticate via LDAP - currently done thru Shiro

### ISSUE THREAD

**Issue by stephanebastian** [eclipse-vertx/vertx-auth#325]

**Comment by pmlopes** [comment]
@stephanebastian, a second task to complete this would be to `deprecate` the shiro provider (just add the annotation everywhere) and update the documentation stating to use the new properties/ldap providers instead.

**Comment by stephanebastian** [comment]
sure. I opened the issue #333 for it and will do a PR asap
