### ISSUE TITLE
User.authorizations() doesn't currently keep track of the AuthorizationProvider that contributed authorizations

### ISSUE THREAD

**Issue by stephanebastian** [eclipse-vertx/vertx-auth#331]
### Version

* vert.x core: 4.0
* vert.x auth: 4.0

### Context

The method User.authorizations() currently returns a set of Authorizations. However, it doesn't allow to keep track of which AuthorizationProvider added Authorizations.
With Vertx 4, it'll be possible to support multiple AuthorizationProvider and it may be important to keep track of the relationship between Authroization -> Set<Authorization>
Therefore I suggest to provide a mechanism to do this. 

### Proposed Solution
I tried several solutions, the simplest one is to modify the signature of authorization so that i returns a Map<String, Set<Authorization>>, where keys are the authorization provider id and values are the set of authorizations contributed by the authorization provider:
```
User {
    ...   
    Map<String, Set<Authorization>> authorizations();
    ...
}
```
However, there seems to be a limitation of vertx-codegen where it's not possible to support this signature.

Therefore I suggest to add the following:

```
@VertxGen
public interface Authorizations {
  @Fluent
  Authorizations add(String providerId, Set<Authorization> authorizations);
  @Fluent
  Authorizations add(String providerId, Authorization authorization);
  @Fluent
  Authorizations delete(String providerId);
  Set<Authorization> get(String providerId);
  Set<String> getProviderIds();
}

```

and update the method User.authorizations() so that it returns Authorizations as below:
User {
    ...
    default Authorizations authorizations() {
	  return new AuthorizationsImpl();
    }
    ...
}

**Comment by pmlopes** [comment]
This has been merged.
