### ISSUE TITLE
OAuth2 site address with the trailing "/" causes the problem with Auth0

### ISSUE THREAD

**Issue by sberyozkin** [eclipse-vertx/vertx-auth#335]
Please see https://github.com/quarkusio/quarkus/issues/5829

If the site address end with "/" then there is a connection error, and if this trailing slash is removed then there is an issuer validation error.

Proposal: when building a discovery URL, check for a duplicate slash, but keep the original site URL and when auto-validating the issuer, check it against the original site URL with the forward slash if any, and without a slash.

**Comment by sberyozkin** [comment]
@pmlopes Hi Paulo, please also fix it for 3.8.x

**Comment by sberyozkin** [comment]
@pmlopes Hey Paulo, that was super fast :-) but the fix is not correct, sorry, because the Auth0 issue validation will not work, Auth0 reports an issue with the trailing slash irrespective of whether the site URL ends with "/" or not. I can't reopen this issue, please reopen it.

**Comment by pmlopes** [comment]
`Oauth2Options` `path` properties are expected to be HTTP paths which are expected to start with `/`. A special case is done when they do not start with slash and in that case are assumed to be a full URL and the `site` property is ignored totally.

**Comment by sberyozkin** [comment]
@pmlopes Those `path` properties which are reported in the Quarkus issue are not relevant here, the user has just tried them to get things working.
The problem is that Auth0 reports an issuer with the trailing slash, irrespective of how one sets a site URL, with or without the slash. 
So the fix is not complete, because now the auto-validation of the issuer will be skipped, see what I mean ?

**Comment by sberyozkin** [comment]
@pmlopes Sorry I'm getting confused a bit, but it does look like the fix is not complete, the user has tried to set the site URL without a trailing slash and it caused an issue validation failure because Vertx Oauth2 compares the site URL against the issuer claim which happens to be the same as the site URL but with the trailing slash.
So it needs a minor tweak, compare with and without a trailing slash, do you agree ?

**Comment by pmlopes** [comment]
https://github.com/vert-x3/vertx-auth/commit/95f0d10e60055a5c46c924a6a09ea637bb570f75

**Comment by UkonnRa** [comment]
Facing the same issue when using [ory hydra](https://github.com/ory/hydra), thanks for the quick update
