### ISSUE TITLE
There is no request token for this page with TwitterAuth

### ISSUE THREAD

**Issue by mklueh** [eclipse-vertx/vertx-auth#354]
Hi there,

I´m running into this issue with the vertx TwitterAuth config:

> Whoa there!
> There is no request token for this page. That's the special key we need from applications asking to use your Twitter account. Please go back to the site or application that sent you here and try again; it was probably just a mistake.

is there anything wrong with the auth flow especially on twitter? It seems the **oauth/request**_token endpoint is entirely missing in the implementation.

**Comment by pmlopes** [comment]
Hi @mklueh can you share a reproducer without the client id/secret you used?

**Comment by mklueh** [comment]
Hi @plmopes

To retrieve the auth url, I do something like this

```
     private String twitter(){
         OAuth2Auth oauth2 = TwitterAuth.create(vertx, "", "");

         JsonObject request = new JsonObject()
                 .put("my_meta_data", "");

         String encode = request.encode();

         return oauth2.authorizeURL(new JsonObject()
                 .put("redirect_uri", callback)
                 .put("state", encode)
         );
     }
```

When I use GitHub for example as options everything works as expected

```
    public OAuth2ClientOptions getGitHubOptions() {
        return new OAuth2ClientOptions()
                .setClientID("")
                .setClientSecret("")
                .setSite("https://github.com/login")
                .setTokenPath("/oauth/access_token")
                .setAuthorizationPath("/oauth/authorize");
    }
```

works as well as

`GithubAuth.create(vertx,"","");`

**Comment by mklueh** [comment]
Hi @pmlopes ,

could you please tell me if I´m doing something wrong or if the auth flow is flawed for Twitter in this library?

**Comment by mklueh** [comment]
Had now time to look into it again and it seems that this implementation doesn´t make sense at all.

Twitter uses oAuth 1a as well as oAuth 2.0, this library is for oAuth 2.0 only but it´s using the Twitter oAuth 1a endpoints. See this implementation from vertx-auth

```
 static OAuth2Auth create(Vertx vertx, String clientId, String clientSecret, HttpClientOptions httpClientOptions) {
    return
      OAuth2Auth.create(vertx, new OAuth2ClientOptions(httpClientOptions)
        .setFlow(OAuth2FlowType.AUTH_CODE)
        .setClientID(clientId)
        .setClientSecret(clientSecret)
        .setSite("https://api.twitter.com")
        .setTokenPath("/oauth/access_token")
        .setAuthorizationPath("/oauth/authorize")
        .setUserInfoPath("/1.1/users/show.json"));
  }
```

According to the Twitter documentation those are clearly 1a URLs

https://developer.twitter.com/en/docs/basics/authentication/api-reference

https://developer.twitter.com/en/docs/basics/authentication/oauth-2-0/application-only

For the vast majority of API features that are accessing private information you need 1a:

> Please note that OAuth 1.0a is still required to issues requests on behalf of users. The API reference page describes the authentication method required to use an API. You will need user-authentication, user-context, with an access token to perform the following

Please correct me if I´m wrong

**Comment by bebsworthy** [comment]
I came to the same conclusion before coming here to search; it seems twitter OAuth2 is only for publicly accessible information and OAuth 1.0a for everything else. I've eventually used twitter4j.

**Comment by pmlopes** [comment]
This module is oauth 2.0 only (so for oauth 1.0a indeed you need to use a different library, sorry)
