### ISSUE TITLE
OAuth2AuthHandler callback causes "Internal Server Error" with Oracle Identity Cloud

### ISSUE THREAD

**Issue by jonathon-eastman** [eclipse-vertx/vertx-auth#358]
### 3.8.4

* vert.x core:
* vert.x auth:

### Context

I trying to create a small web app that get the user's credentials using OAuth2 provided by the Oracle Identity Cloud Service.   Oracle uses three legged OAuth2 and also extends it with OpenID.   Using curl I was able to validate that everything works (Basically everything in my OAuth2ClientOptions is correct)   I've tried both using OAuth2 and the OpenId methods.  Both use Authorization code flow.  I was able to get the access_token and userinfo no problem.

Anyways, the simple project I uploaded to github uses OAuth2AuthHandler.    This correctly  authorizes to the authorization url but fails to get the  access_token at the token url.  It fails in the browser at the callback and the browser returns "Internal Server Error". 

### Do you have a reproducer?

https://github.com/jonathon-eastman/oauth

Although I think reproducing would be difficult without an Oracle account.  Let me know if there is anything I can do to alleviate this issue.

### Steps to reproduce

1. run project the maven project that creates localhost http server at port 9012.
2. goto url http://localhost:9012/private/sercret
3. this successfully authorizes with Oracle Identity cloud and returns a code to get the access_token.
4.  the callback to http://localhost:9012/callback isn't handled by OAuth2AuthHandler and produces a "Internal server error" inside the web browser.  Also the browser's url displays the callback.   "http://localhost:9012/callback?code=VERYLONGCALLBACK_RANDOMSTRING&state=1234"
5.  I never get my access_token so I cannot retrieve userinfo.

### Extra

Here is the link to the oracle documentation leveraging OpenId.
[oracle oauth2 extending openid ](https://docs.oracle.com/en/cloud/paas/identity-cloud/rest-api/openidconnectauthcode.html)

here is a link to the overall Oracle Oauth2 documentation:
[oracle oauth2](https://docs.oracle.com/en/cloud/paas/identity-cloud/rest-api/OATOAuthClientWebApp.html)

I may be over my head but I think there is a bug or something not handled in the OAuth2AuthHandler.   I was thinking I need to create my own OracleAuth provider interface.

I appreciate any help.   BTW... Love VERT.X!!!

Thanks,

Jonathon

**Comment by jonathon-eastman** [comment]
I've done more digging on my side.  I used HTTPToolkit and found that it received a 200 response code from the /oauth2/v1/authorize url but it never attempts to reach the /oauth2/v1/token url to get the access_token.  Not sure why.  It looks like it should try in the setupCallback method when it runs the authProvider.authenticate method.

Also as a side note, I dug deeper and looked at the OAuth2API class.  It appears everything headers/parameters look the same as my curl test case for the Token method.

**Comment by pmlopes** [comment]
@jonathon-eastman I'm having some trouble to figure out what the issue is. Could you set up an account where I can connect to a try to debug the application? You can ping me privately on https://gitter.im/eclipse-vertx/vertx-users
