### ISSUE TITLE
Auth options

### ISSUE THREAD

**Issue by vietj** [eclipse-vertx/vertx-auth#36]
at the moment in Vert.x Shell we create auth from options, it would be good to have them in this project for 3.2 instead, see : https://github.com/vert-x3/vertx-shell/tree/master/src/main/java/io/vertx/ext/shell/auth

**Comment by pmlopes** [comment]
:+1: want me to move the code there?

**Comment by vietj** [comment]
yes.

also it should be completed with extra options AuthOptions subclasses for auth mechanisms other than Shiro. If you can't then just create another github issue for it.
