### ISSUE TITLE
ID Token Signature is not verified and any random json is returned as valid ID token 

### ISSUE THREAD

**Issue by Pitambari** [eclipse-vertx/vertx-auth#364]
Version: 3.8.4 and 3.9

Context: ID Token Signature is not verified and any random json is returned. ID token is expected to be a JWT as per OIDC spec. https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse

If someone sent IDToken as a JsonObject and not as JWT, the library accepts JsonObject without validating the signature of the ID Token and treats this as a valid ID token. This is a security issue.

OAuth2UserImpl.java: 

  protected JsonObject decodeToken(String tokenType, boolean trust) {

    final Object opaque = principal.getValue(tokenType);

    if (opaque == null) {
      return null;
    }

    if (opaque instanceof JsonObject) {
      // already decoded
      return (JsonObject) opaque;
    }

Steps to reproduce:
1) Return OIDC token in wrong format where ID token is Json instead of JWT: 
{
   "access_token": "SlAV32hkKG",
   "token_type": "Bearer",
   "refresh_token": "8xLOxBtZp8",
   "expires_in": 3600,
   "id_token": {
  "iss": "http://server.example.com",
  "sub": "248289761001",
  "aud": "s6BhdRkqt3",
  "nonce": "n-0S6_WzA2Mj",
  "exp": 1311281970,
  "iat": 1311280970
}
  }

2) Expected: ID token signature should be validated and if signature is valid return the payload.
3) Actual: ID token signature is not validated and JsonObject is simply returned as valid ID token.

**Comment by pmlopes** [comment]
The PR linked to this issue ensures that decoded tokens are stored on a different area which is independent from the source of the token.

**Comment by Pitambari** [comment]
When is milestone 4.0 expected to be released? Could we have this fix released in current version 3.8.4 or 3.9? this is a critical security bug in the current version.

**Comment by pmlopes** [comment]
3.9 is already planned to be released this week. The bug can be a security bug but it requires several things to happen before to make it critical imho.

1. your idp server must be suffering a MITM attack (which should already require a SSL break)
2. your idp does not emit the spec compliant json responses ("access_token" and "id_token" are json values instead of strings)

Anyway, I'm re-opening and attempt to have it on 3.9
