### ISSUE TITLE
[OpenID Connect] Remove `token_introspection_endpoint` when using OIDC Discovery

### ISSUE THREAD

**Issue by UkonnRa** [eclipse-vertx/vertx-auth#375]
### Questions

As the [OIDC Spec](https://openid.net/specs/openid-connect-discovery-1_0.html), `token_introspection_endpoint` is not a valid field in `/.well-known/openid-configuration`

So [this line](https://github.com/vert-x3/vertx-auth/blob/8b02d4956a626a68a4f8cd5572dc40389fa844c8/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/providers/OpenIDConnectAuth.java#L89) should be removed, and allow user to set `introspectionPath` in another way.

### Version

Vertx: 4.0.0

**Comment by pmlopes** [comment]
That's correct, introspection is a oauth2 feature.
