### ISSUE TITLE
[Introspection Response] `bearer` is not the only Access Token Type

### ISSUE THREAD

**Issue by UkonnRa** [eclipse-vertx/vertx-auth#376]
### Questions

As for [the OAuth2 Introspection Spec](https://tools.ietf.org/html/rfc7662#section-2.2) and [Access Token Spec](https://tools.ietf.org/html/rfc6749#section-7.1), `bearer` is not the only Access Token Type.

So [this assertion](https://github.com/vert-x3/vertx-auth/blob/7beee04d0dcf13c1b1ba30ac916646e777399812/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2AuthProviderImpl.java#L147) may be removed.

In fact, it seems that some OAuth2 Provider (like [Ory Hydra](https://www.ory.sh/docs/hydra/sdk/api#schemaoauth2tokenintrospection)) may use the custom Access Token Types. So this field should not be asserted at all 

https://github.com/ory/hydra/issues/1762 is the related issue

**Comment by pmlopes** [comment]
@UkonnRa thanks for noticing this. so if the response is: `access_token` or `refresh_token` should we validate that it matches what we requested? So in the code fragment you linked, should it verify if present and is `access_token` as that was the requested type?

**Comment by UkonnRa** [comment]
In fact, I am new to OAuth2, so I cannot quite understand how to use the field `token_type`. The point is that, `token_type` seems an implement-specific field, which means that the possible values are based on the implemention. So maybe this field shoule not be checked by the library, but users themselves?

**Comment by pmlopes** [comment]
Yes, most of the APIs are marked as "should", so sometimes is hard to get it right in a way that works for everyone...

**Comment by pmlopes** [comment]
So I guess if we request to introspect a `access_token` then we should not allow if the response is `refresh_token` as it feels like we're not getting what we asked. But again it's like you wrote, should we (users) do this?

**Comment by UkonnRa** [comment]
Well, it would be great if I can handle it myself, because the library have no idea what the possible values would be.
