### ISSUE TITLE
Code grant request fails when OIDC server returns an opaque access token

### ISSUE THREAD

**Issue by sberyozkin** [eclipse-vertx/vertx-auth#381]
See https://github.com/quarkusio/quarkus/issues/8396.

(Auth0 docs do not recommend verifying the access token returned as part of the code grant since it is meant to be used by the client and as such as should be treated as opaque, it is id token which must be jwt)

I'd like to do a small PR which will add `OAuth2ClientOptions.verifyCodeFlowAccessToken` property, default is `true` to keep the current code working as expected, but if it is `false` then the access token is not verified.

**Comment by pmlopes** [comment]
Looking at the `auth0` docs: https://auth0.com/docs/tokens/concepts/access-tokens

The docs state that you can have 2 kinds of tokens:

* `opaque`
* `jwt`

Also on the `jwt` section you can read:

> Access Tokens issued for the Auth0 Management API and Access Tokens issued for any custom API that you have registered with Auth0 will follow the JSON Web Token (JWT) standard, which means that their basic structure conforms to the typical JWT Structure, and they contain standard JWT Claims asserted about the token itself.

I'm removing the `bug` label based on this.

**Comment by sberyozkin** [comment]
@pmlopes OK, so yes, it is not a bug as I know now in that Vertx, by verifying the code flow AT, be it opaque or JWT token, does not cause a linked Quarkus issue. The Auth0 doc which is relevant is:
```
Remember that an Access Token is meant for an API and should be validated only by the API for which it was intended. Client applications should not depend on the Access Token to be any specific format, and instead treat it as if it is opaque (regardless of whether it actually is).
```
In Quarkus case, OOB, AT is not meant for the Quarkus endpoint, only IdToken is, AT - is for Quarkus endpoint to propagate. 

So this issue is really about letting such Quarkus endpoints not to do any checks on the ATs in the code flow at all.  

But this is a vague area I have to say, in that in some cases the users may treat both token types interchangeably.

So let me close this issue and I'll ping you if we get the users asking for it...

Thanks
