### ISSUE TITLE
Credentials#checkValid breaks Rxified API generation

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-auth#404]
Rxified API generation is broken since #401 has been merged.

The issue is with Credentials#checkValid

https://github.com/vert-x3/vertx-auth/blob/e136eb6d9b5dfcfeba55e2ca2370982f8337964c/vertx-auth-common/src/main/java/io/vertx/ext/auth/authentication/Credentials.java#L38-L39

The generated method does not declare the thrown checked exception and thus fails to compile. I'm not sure `codegen` supports thrown exceptions ATM.

**Comment by pmlopes** [comment]
The exception is now runtime.
