### ISSUE TITLE
generateToken() throws NoSuchMethodError in 3.9.2

### ISSUE THREAD

**Issue by jymboche** [eclipse-vertx/vertx-auth#408]
### Version

3.9.2

### Context

While following the official docs and creating a token as follows I get a NoSuchMethod Error:
```
        val provider = JWTAuth.create(vertx, authConfig)
        val token = provider.generateToken( json {
            obj("sub" to "paulo")
        }, JWTOptions(algorithm = "ES256"))
```
```
SEVERE: io.vertx.ext.auth.jwt.JWTAuth.generateToken(Lio/vertx/core/json/JsonObject;Lio/vertx/ext/jwt/JWTOptions;)Ljava/lang/String;
java.lang.NoSuchMethodError: io.vertx.ext.auth.jwt.JWTAuth.generateToken(Lio/vertx/core/json/JsonObject;Lio/vertx/ext/jwt/JWTOptions;)Ljava/lang/String;
	at io.vertx.reactivex.ext.auth.jwt.JWTAuth.generateToken(JWTAuth.java:90)
```

If I downgrade to lower versions including 3.9.1 I dont encounter the error.

**Comment by pmlopes** [comment]
Can you create a reproducer? It looks like you have a version alignment issue. Maybe corrupted artifact cache.

**Comment by jymboche** [comment]
Yep, you were right.... i started working on a reproducer and realized i got pretty far along using the rx api without actually including the vertx-rx-java2 dependency somehow....whoops!
