### ISSUE TITLE
SQL Client Auth not available in Rxified API

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-auth#412]
I haven't checked but  it might be absent from Kotlin and Groovy too.

**Comment by pmlopes** [comment]
Fixed by:

https://github.com/vert-x3/vertx-rx/commit/f8149e7625b3bee7d1a558d49c4b4b80792fead8
https://github.com/vert-x3/vertx-rx/commit/d4bcb100a8e96491a6c4918f13739c38b6fada4d

and kotlin too.
