### ISSUE TITLE
Webauthn/FIDO2 MDS service

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-auth#415]
The current webauthn support covers almost all the compliance tests, except `MDS`. It would be interesting for the sake of completion to have an implementation on vertx webauthn too.

https://fidoalliance.org/metadata/

https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-metadata-service-v2.0-id-20180227.html

This service should load and validate a TOC and allow queries on the metadata.

**Comment by anuranjit** [comment]
@pmlopes Want to help . Came here from your gitter message .

**Comment by pmlopes** [comment]
Hi, great!

The goal here is to have a "service" that will download the FIDO2 toc file.

This file is a jwt. Once it's downloaded and valid, one needs to iterate the payload and download the statements.

Statements are json files. One needs to be safe and download only from trusted servers. After you need to verify the integrity of the json. The hash must match the toc.

Once this succeed, you can put it on the metadata repository. 

Finally the toc or the statements have an expiration date, so we need a periodic task to restart the process as a whole, or just for a specific statement. 

We can't use vertx-web-client, we must use vertx-core (like in oauth2) to avoid having cyclic dependencies. 

@anuranjit if you still want to help, let me know and we can discuss further. In the meantime try to have a look at the links above, but don't worry too much if it's hard to grasp. This service is only about having the metadata up to date on our side. The usage of metadata is a different issue.

:wink:

**Comment by anuranjit** [comment]
@pmlopes thanks. Will look at the links . FYI Still want to help 😀

**Comment by pmlopes** [comment]
Great, if you want to get some inspiration on how to start, try to follow the oauth2 code on the jwkSet refresh

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2AuthProviderImpl.java#L74

It downloads a single json and set a periodic task to update it if needed.

**Comment by pmlopes** [comment]
Once the TOC is parsed and validated it should download the metadata json files and pass them to:

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-webauthn/src/main/java/io/vertx/ext/auth/webauthn/impl/attestation/Metadata.java#L191

`Metadata.loadStatement()`

Later we can add more methods, like `clear()`, `removeStatement(String aaguid)`, etc...

**Comment by anuranjit** [comment]
@pmlopes  Ok. Trying to understand the entire flow. Can i ping you on gitter if required ?

**Comment by pmlopes** [comment]
@anuranjit sure.

**Comment by pmlopes** [comment]
Depends on: https://github.com/vert-x3/vertx-auth/issues/418

**Comment by pmlopes** [comment]
@anuranjit I've moved the internal http client to common, so you can use it to fetch the MDS toc:

```java
final SimpleHttpClient httpClient = new SimpleHttpClient(
      vertx,
      "vertx/webauthn",
      new HttpClientOptions());

httpClient.fetch(
  httpClient.fetch(
      HttpMethod.GET,
      mdsServerUrl,
      new JsonObject()
        .put("Accept", "application/json"),
      null,
      fetch -> {
 ...
});
```

And from there proceed with the toc validation.

The toc is a jwt, so you need:

```java
JsonObject jwt = new JWT().allowEmbeddedKey(true).decode(downloadedTocBuffer);
```
