### ISSUE TITLE
authenticate fails when id_token is null in client credential flow

### ISSUE THREAD

**Issue by miriampe** [eclipse-vertx/vertx-auth#416]
Version: 3.9

during client credential flow authentication, I encountered a problem, when id_token is null OAuth2UserImpl fails on validation.
I think is a bit brittle especially for client credentials where  id token is never expected.

`       
public OAuth2UserImpl(OAuth2Auth provider, JsonObject principal) {

    this.principal = principal;
    // mitigate broken tokens
    if (
      !(principal.getValue("access_token" , "") instanceof String) ||
      !(principal.getValue("id_token", "") instanceof String)) {
      // the token doesn't contain a string based value for the given claims
      throw new IllegalStateException("Tokens are not valid base64 strings");
    }
    setAuthProvider(provider);
  }

`

**Comment by pmlopes** [comment]
This code has been refactored.
