### ISSUE TITLE
Add collection and updates of JWKS from OIDC/Oauth providers

### ISSUE THREAD

**Issue by pendula95** [eclipse-vertx/vertx-auth#417]
#### Describe the feature

When creating AuthHandler that is used to validate external JWTs, example Keycloak generated JWTs, best way to achieve this is to get info from .well-know and obtain info from jwks_uri uri and load keys. This is done on startup of the app and auth handler is generated with fix values obtained on start of application. During the lifetime of application JWT provider might change/add/remove keys that are used and this new info is not obtained.
It would be good to add background scheduler/updated to periodicly update JWKS in generated auth handler. Some configuration should be specified to support this. This can be done for any Oauth2 or OIDC provider. 

#### Contribution

Idea is here to agree on configuration and feature and agree on specification. I would be able to submit the PR once we agree on details.

**Comment by pmlopes** [comment]
Hi @pendula95, isn't this already covered by: https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/OAuth2Auth.java#L56-L69 ?

**Comment by pendula95** [comment]
Looks like my bad, I was looking for this feature at a wrong place. This is defined under oAuht2. One question before I close this. If I create OAuth2Auth using OpenIDConnectAuth is everything for automatic update of jwks done for me or I need to do something more?

**Comment by pmlopes** [comment]
Well, it should. The oidc discovery sets up all the config based on the downloaded info, including jwks.

If it doesn't, it can be a bug as this is quite recent since 3.9 if I'm not mistaken.

**Comment by pendula95** [comment]
I will test this out and update on this tread.
