### ISSUE TITLE
Add an option to specify the signing algorithm

### ISSUE THREAD

**Issue by lascarayf** [eclipse-vertx/vertx-auth#42]
Actually the signing algorithm is the same as the certificate, but in some cases you must use another.

``` java
  CryptoSignature(final X509Certificate certificate, final PrivateKey privateKey) {
    this.certificate = certificate;
    this.privateKey = privateKey;
    try {
      this.sig = Signature.getInstance(certificate.getSigAlgName());
    } catch (NoSuchAlgorithmException e) {
      throw new RuntimeException(e);
    }
  }
```

In the "Google Cloud Plataform" we need to sign the JWT with **SHA256withRSA** using the private key of PKCS#12 certificate. The certificate is generated by Google and the sign algorithm of certificate is **SHA1withRSA** :(

https://developers.google.com/identity/protocols/OAuth2ServiceAccount

**Comment by pmlopes** [comment]
I'm not sure if i understand, if you import the certificate google creates for you and name it RS256 when you need to generate tokens you can always do:

``` java
jwt.generateToken(new JsonObject(), new JWTOptions().setAlgorithm("RS256"))
```

But you're saying that the cerficate Google issues is not SHA256+RSA but SHA1+RSA? Could you get me a test certificate so I can test it then?

**Comment by pmlopes** [comment]
I've created a test certificate and it now gets signed with the desired algorithm. @lascarayf can you review it?

**Comment by lascarayf** [comment]
Hi @pmlopes I just test the branch and it worked perfectly :) 

Thanks !!!
