### ISSUE TITLE
In 3.x leeway is not taken into account when testing for oauth2 user expiry

### ISSUE THREAD

**Issue by steven-aerts** [eclipse-vertx/vertx-auth#431]
### Version

3.x

### Context

In most cases of checking JWT token expiry a leeway option is taken into account.
But not when checking an Oauth2 user for expiry.  

### Do you have a reproducer?

A fix with test cases which reproduce the issue is coming up.

### Steps to reproduce

Configure an oauth2 provider with the leeway parameter in its JWTOptions.  And come in with an token which is just expired.

### Extra

This behavior is working/fixed in 4.0 as it uses a different implementation does it correctly (looking at the code)

**Comment by pmlopes** [comment]
Fixed by #432
