### ISSUE TITLE
UserConverter does not take into account the attributes field

### ISSUE THREAD

**Issue by thced** [eclipse-vertx/vertx-auth#441]
Version 4.0.0

### Context

While serializing a user to/from Hazelcast via ClusteredSessionStore, I noticed that when encoding/decoding the User (UserImpl) there was information available on the User when encoding it, but that information is lost (and not even available) when decoding it. The `attributes` field is not considered at all in the UserConverter (by first, simply looking at the static fields in the class).

**Comment by pmlopes** [comment]
Fixed by #442
