### ISSUE TITLE
Update docs related to hashing

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-auth#443]
In 4.0.0 the hashing strategies have changed to be standard compliant and more secure, however the docs/javadoc is not clear about this:

https://gitter.im/eclipse-vertx/vertx-users?at=5fdb7fc05fd1424015150a85

We should update docs + javadoc with info:

https://gitter.im/eclipse-vertx/vertx-users?at=5fdb81b74e3d554d67819bd9
https://gitter.im/eclipse-vertx/vertx-users?at=5fdc68fd8bb73474693de00d

And any other relevant information!

**Comment by vietj** [comment]
@pmlopes any progress on this ?
