### ISSUE TITLE
HttpHeaders duplicated

### ISSUE THREAD

**Issue by DemonicTutor** [eclipse-vertx/vertx-auth#444]
### Version

4.0.0

### Context

OAuth2Auth.authenticate() with OAuth2Options containing `headers` these headers will be set twice.

### Steps to reproduce

1. token() adds headers from config [here](https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2API.java#L177)
2. token calls fetch() with those headers
2. fetch() adds headers from config [here](https://github.com/vert-x3/vertx-auth/blob/688e8a723ce798e98ad2419a8d40d296cf74ce96/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2API.java#L563)
3. makeRequest is called with options containing duplicated header from config

**Comment by pmlopes** [comment]
Fixed by #445
