### ISSUE TITLE
JWT verification is broken if secret contains only non-ascii characters 

### ISSUE THREAD

**Issue by u6f6o** [eclipse-vertx/vertx-auth#448]
### Version

4.0.0

### Context

We are using random byte arrays for our symmetric key secrets. I tried to replace our existing jwt verification, which is using [jjwt](https://github.com/jwtk/jjwt) by vertx solutions instead. Integrating these solutions, I recognised, that my jwts which are issued by another service cannot be verified. 

After some digging in the vert.x code I found out, that the key secret is transformed into an us-ascii byte array [here](https://github.com/vert-x3/vertx-auth/blob/7e94c383479a02e3e400d2ce3e755a3f028ce87a/vertx-auth-common/src/main/java/io/vertx/ext/auth/impl/jose/JWK.java#L183 ). This is bad, as every character of my secret was replaced by (byte)63. 

This is a security issue as well, as the verification can be easily broken if the secret contains only of non-ascii characters, as shown in my reproducer. 

### Do you have a reproducer?

Yes, [here](https://github.com/u6f6o/vertx-jwt-bug/blob/master/src/test/kotlin/JwtTest.kt). 

### Steps to reproduce

1. Clone the project
2. Fetch dependencies using gradle
3. Run JwtTest.kt

**Comment by u6f6o** [comment]
I'd like to add a suggestion how to solve this issue. Instead of adding a flag to decide which charset to use (as discussed), I think it's better to offer an option to provide the secret as a byte array instead. This way, the charset can be omitted entirely. Also for the folks using the current string approach, it would still work by transforming the string secret internally into a byte array using the us-ascii charset as done atm. 

In order to store the key somewhere, one could transform it to a base64 encoded representation and decode it back into the byte array when needed for the jwt generaten/verification without dealing with charsets and the like. In the library we are currently using, it also works this way: 

```
val secretByteArray = Decoders.BASE64URL.decode(base64EncodedSecret)
val secretKey = Keys.hmacShaKeyFor(secretByteArray)
return Jwts
      .parserBuilder()
      .setSigningKey(secretKey)
      .setAllowedClockSkewSeconds(TimeUnit.MINUTES.toSeconds(1))
      .build()
```

**Comment by pmlopes** [comment]
I've a proposal that uses UTF8 for secrets, which should cover this use case. In order to allow any characters, indeed using a `Buffer` would be preferable. I need to see if we can change the underlying holder from `String` to `Buffer` without breaking the public API.

**Comment by pmlopes** [comment]
The current state handles both `buffer`s and `string`s. So we have full backward compatibility and support for any kind of secrets (`byte[]`).

**Comment by u6f6o** [comment]
I wrote a little test that verified ~1000 jwts from our development environment using the new approach. The jwts have been issued on other services, using the jjwt library.  So for me it looks all good 👍
