### ISSUE TITLE
mongoAuth.insertUser creates multiple users with he same name

### ISSUE THREAD

**Issue by BorisBorshevsky** [eclipse-vertx/vertx-auth#45]
mongoAuth.insertUser creates multiple users with the same name causing authentication to fail.
i would expect that insertuser will validate that the same user does not exists.

**Comment by pmlopes** [comment]
A quick workaround is to create a unique index:

```
db.collection.createIndex( { username: 1 }, { unique: true } )
```

**Comment by BorisBorshevsky** [comment]
works perfectly! thanks.

**Comment by pmlopes** [comment]
I'll add this info to the documentation since it is the only guaranteed way to have uniqueness in mongo. Mongo has no transactions, so doing first a query for existance and then insert could lead more than 1 entry being inserted with the same username.
