### ISSUE TITLE
WebAuthn : Relying parties should collect, store, and validate attestation certificates.

### ISSUE THREAD

**Issue by tcompiegne** [eclipse-vertx/vertx-auth#456]
#### Describe the feature

As part of the Yubico documentation : https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Attestation.html

```
Relying parties should collect, store, and validate attestation certificates. 
Attestation certificates contain metadata such as the device name, supported transports, image url, etc. 
This metadata can be retrieved by the RP to enable granular attestation certificate authority management, customize user experiences based on supported transports, and report authenticator metrics in your environment. 
Additionally, a trust store containing all registered attestation certificates provides an audit trail to support high assurance MFA.
```

@pmlopes what are you thoughts about it ? currently we only store data of the authenticator and not the attestation.

Could be useful if we want to reject a previous registered device by checking the FIDO metadata service. 

Best regards.

**Comment by pmlopes** [comment]
Currently we support the MDS service as per FIDO2. This is the setup used during the certification step of the library:

```java
    // fido2 compliance test adaptor
    final WebAuthnOptions webAuthnOptions = new WebAuthnOptions()
      .setRelyingParty(
        new RelyingParty()
          .setId(rpId)
          .setName("Vert.x Compliance Test"))
      .putRootCertificate(
        "mds",
        "MDS certificate")
      .addRootCrl(
        "MDS CRL #1")
      .addRootCrl(
        "MDS CRL #2");

    // create the webauthn security object
    final WebAuthn webAuthN = WebAuthn.create(vertx, webAuthnOptions)
      // where to load/update authenticators data
      .authenticatorFetcher(database::fetcher)
      .authenticatorUpdater(database::updater);

    FileSystem fs = vertx.fileSystem();

    // Load a preset of cached metdata statements

    for (String f : fs.readDirBlocking("metadataStatements")) {
      webAuthN.metaDataService()
        .addStatement(new JsonObject(fs.readFileBlocking(f)));
    }

   // and add even more MDS entries, this time by using the official MDS REST API, we can have multiple sources:

    // add MDS servers
    String[] servers = new String[]{
      "https://mds.certinfra.fidoalliance.org/execute/...1",
      "https://mds.certinfra.fidoalliance.org/execute/...2",
      "https://mds.certinfra.fidoalliance.org/execute/...3",
      "https://mds.certinfra.fidoalliance.org/execute/...4",
      "https://mds.certinfra.fidoalliance.org/execute/...5"
    };

    final AtomicInteger cnt = new AtomicInteger(servers.length);

    for (String url : servers) {
      webAuthN.metaDataService()
        .fetchTOC(url)
        .onFailure(err -> {
          System.out.println("Ignoring: " + url + " - " + err.getMessage());
        })
        .onSuccess(allOk -> {
          System.out.println("All OK: " + allOk);
        });
    }
```

This will verify any registration against the service. Is this what you're looking for? Or are you looking for a way as a second external process, go over the authenticator store and recheck against the MDS?

In that case we could enhance the store to hold some extra data (maybe the source attestation). This would also require some internal code changes as we would need to parse the attestation and skip the attestation up to the MDS checks. This is attestion specific as in some case the MDS is just the last operation, but it can also occur early in the overall check.

**Comment by tcompiegne** [comment]
`Or are you looking for a way as a second external process, go over the authenticator store and recheck against the MDS?`

=> Exactly.

`In that case we could enhance the store to hold some extra data (maybe the source attestation).` 

=> Yes same here, I think we have to store the input required for the MDS check process.

**Comment by tcompiegne** [comment]
Thanks @pmlopes , appreciate it.

Regards
