### ISSUE TITLE
JWT public and private key parsing issue

### ISSUE THREAD

**Issue by tipok** [eclipse-vertx/vertx-auth#459]
Hi,

We run into an issue using JWT in our product, because loading of the public key ran into the exception. We added a workaround for it, but it might be worth fixing.

In the switch/case there is case for `PRIVATE RSA KEY` and `PUBLIC RSA KEY`, which seems not to be the default format for the pre/postfix.
The default format seems to be `RSA PRIVATE KEY` and `RSA PUBLIC KEY`.

https://github.com/vert-x3/vertx-auth/blob/ee361aeec879f2e707d372883efb1b3214aecde1/vertx-auth-common/src/main/java/io/vertx/ext/auth/impl/jose/JWK.java#L304

https://github.com/vert-x3/vertx-auth/blob/ee361aeec879f2e707d372883efb1b3214aecde1/vertx-auth-common/src/main/java/io/vertx/ext/auth/impl/jose/JWK.java#L308

**Comment by tipok** [comment]
If you think it would be a good fix, I would be happy adding a PR for it.

**Comment by pmlopes** [comment]
@tipok thank you for spotting it out. Please do make a pull request!
