### ISSUE TITLE
Forced JWK refresh if JWK id is missing And Configurable ClientId Validation in Introspection

### ISSUE THREAD

**Issue by vishu184** [eclipse-vertx/vertx-auth#468]
### Version

* vert.x core:4.0.3
* vert.x auth:4.0.3

### Context

I Have Integrated OAuth2 OpenId Connect which JWKs are rotating at every 24 hours and OpenId Connect Provider is Supporting max-age Header in initial jwk key setup call. so after 24 hours all token jwk key is missing so token introspection is forced. And token intospection response is giving client_id in response so after token introspection client_ id validation is happening which is matches OAuth2Auth config client_id with introspection response client_id which is not same in my case.

beacause in my case token is generating from different (public) client and introspection is happening using different client (at backend).

package io.vertx.ext.auth.oauth2.impl;

Class OAuth2AuthProviderImpl

// validate client id
            if (json.containsKey("client_id")) {
              // response included a client id. Match against config client id
              if (!config.getClientID().equals(json.getString("client_id"))) {
                // Client identifier for the OAuth 2.0 client that requested this token.
                handler.handle(Future.failedFuture("Wrong client_id"));
                return;
              }
            }

**Comment by pmlopes** [comment]
@vishu184 can you detail which provider is this?

The introspection response may contain a `client_id` as per RFC: https://tools.ietf.org/html/rfc7662

Can you share what kind of response you also get versus what you're configuring as `clientId`?

**Comment by vishu184** [comment]
@pmlopes Authentication Provider is PingIdentity

yes introspection response may contain client_id but when it is contain vertx-auth-oauth2 force to validate OAuth2Auth clientId with introspection response clientId.

my OAuth2Auth clientId : internal
intropsection response client_id: web_app

**Comment by pmlopes** [comment]
After reading the RFC again, I see that there's no specific mention that the `client_id` must match the client, it just says it may be present. So, I think we should remove that check in total.

Another think we should do is add a leeway time for jwt refresh. If the refresh is set then we start the process a few seconds before to avoid disruption.

**Comment by pmlopes** [comment]
@vishu184 once the PR passes the CI tests, can you try to verify on your end if this good enough?

**Comment by vishu184** [comment]
@pmlopes sure Thanks...

And about JWK refresh we need to forced Refresh whenever key is missing because most of the OpenId Connect Provider is not providing max-age attribute in Cache-Control header of jwks Response

**Comment by vishu184** [comment]
@pmlopes 

In My Case My ms is performing for set number of hours properly and when jwk rotating authentication starts to fail because jwk key is missing and token is getting introspect.

**Comment by pmlopes** [comment]
@vishu184 I've updated the javadoc and added a test showcasing how to implement "auto-refresh":

```java
    // are we already updating the jwks?
    final AtomicBoolean updating = new AtomicBoolean(false);
    oauth2
      // default missing key handler, will try to reload with debounce
      .missingKeyHandler(keyId -> {
        if (updating.compareAndSet(false, true)) {
          System.out.println("Refreshing JWKs due missing key [" + keyId + "]");
          oauth2.jWKSet(done -> {
            updating.compareAndSet(true, false);
            if (done.failed()) {
              System.out.println("Refresh JWKs failed: " + done.cause());
            }
          });
        }
      })
 ```

I am a bit reluctant to have it as default behavior for a couple of reasons.

* there's no generic way to know if the missing key is correct or an attack to the app
* There's no control if the error is because the key doesn't exist regardless of the update
* There's no error counter so if the IdP is down we may be making things worse

All these and other situations could lead to a DDoS which is why I believe it should be the user's responsibility to decide how to implement it.

**Comment by pmlopes** [comment]
No matter what during refresh the module will fall back to introspection mode for missing keys. This avoids queueing on the application side which prevents snowball effect on resource usage at the application server.

**Comment by vishu184** [comment]
Thank you I understand implementation behavior I am closing this issue as it is solved.
Thank you for solving issue within couple of hours.....

**Comment by pmlopes** [comment]
Well, I should merge the PR first ;-)
