### ISSUE TITLE
OAuth2AuthProviderImpl loadJWK loads continuously even after object is de-referenced

### ISSUE THREAD

**Issue by narras-oss** [eclipse-vertx/vertx-auth#503]
### Version

3.9.8

### Context

We use this module in production and create and cache OAuth2Auth object for 1/2 hour for each provider. One of the providers returns maxAge as 15 seconds in cache control response header. We noticed that over time the number of calls keeps increasing in a step fashion. The logic in the loadJWK method seems to be creating a periodic timer in vertx which calls loadJWK with delay = maxAge cache control header. And there is no way to disable this refresh or to stop the timer if the object is de-referenced. Over several days the call count builds up to 1000 / min.

### Do you have a reproducer?

Yes. Attaching simple mvn spring boot project
Command to build: "mvn clean package"
Command to run: "java -jar target/vertx-oauth-timer-reproduce-1.0-SNAPSHOT.jar"

### Steps to reproduce

1. Create multiple oAuth2Auth objects and call loadJWK once. Make sure JWKS URL points to a server that returns a low value of maxAge (say 1 second)
2. After these objects are created, de-reference them by exiting the method that created them
3. Check vertx http client metrics to see number of calls generated

**Comment by narras-oss** [comment]
[vertx-oauth-timer-reproduce.zip](https://github.com/vert-x3/vertx-auth/files/7095252/vertx-oauth-timer-reproduce.zip)

**Comment by narras-oss** [comment]
Some recommendations:

1. If maxAge < minimum configured refresh interval, then use minimum configured refresh interval
2. Make refresh optional, let clients manage this

**Comment by pmlopes** [comment]
We need to introduce a close/destroy method to cancel any running timers
