### ISSUE TITLE
MongoAuth 4.1.x does not use custom property names correctly

### ISSUE THREAD

**Issue by sophokles73** [eclipse-vertx/vertx-auth#506]
### Version

MongoAuth 4.1.4

### Context

When setting the *usernameCredentialsField* and *passwordCredentialsField* configuration properties on class MongoAuthenticationOptions to custom values, then the authentication of a credentials JsonObject using the configured property names fails.

### Do you have a reproducer?

No, but I have a PR fixing the issue.

**Comment by pmlopes** [comment]
Thanks!
