### ISSUE TITLE
JWK: Exception when using legacy vert.x Json Base64 encoder/decoder

### ISSUE THREAD

**Issue by calohmn** [eclipse-vertx/vertx-auth#510]
In our application, we have set the `vertx.json.base64` system property to `legacy`, in order to use the Json Base64 encoder/decoder that is compatible with vert.x 3.

Upgrading to vert.x 4.x, we now get an `IllegalArgumentException: Illegal base64 character` exception when instantiating a `io.vertx.ext.auth.impl.jose.JWK` with a `JsonObject` parameter.

The `JWK` class in vert.x 3.x was using the `Base64.getUrlDecoder()` decoder to decode the base64 JsonObject fields (i.e. the "new" vert.x 4 decoder).
With vert.x 4, the `JWK` class will now use the decoder used by `JsonObject.getBinary()` which will be the legacy `Base64.getDecoder()` decoder if `-Dvertx.json.base64=legacy` is set (see [here](https://github.com/vert-x3/vertx-auth/commit/cba8054e800e97c80e575e627eb6098fae5c32ed#diff-a3cbfe6a427dfce5cea09ea63d0d7bde50ad74eef288f45ee5843e1152ec8ec9R494)).

FMPOV, setting `-Dvertx.json.base64=legacy` shouldn't introduce a change in behaviour here - the vert.x 3.x `JWK` class wasn't using the "legacy" decoder in the first place.

### Version

vertx-auth-common:4.1.3

### Context

`-Dvertx.json.base64=legacy`

### Steps to reproduce

Take the "[io.vertx.ext.auth.JWKTest](https://github.com/vert-x3/vertx-auth/blob/d4c32288739d4e8a14cbf3adaf0be652b4aa0b75/vertx-auth-common/src/test/java/io/vertx/ext/auth/JWKTest.java)" class and add
```
  static {
    System.setProperty("vertx.json.base64", "legacy");
  }
```
Several tests then fail with an exception like:
```
java.lang.IllegalArgumentException: Illegal base64 character 5f
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at io.vertx.core.json.JsonObject.getBinary(JsonObject.java:308)
	at io.vertx.ext.auth.impl.jose.JWK.createRSA(JWK.java:443)
	at io.vertx.ext.auth.impl.jose.JWK.<init>(JWK.java:381)
```

**Comment by pmlopes** [comment]
This requires updating auth-common and auth-webauthn modules to not use the method `.getBinary()` and always use the correct encoding.
