### ISSUE TITLE
OAuth2WebClient password flow shouldn't require a clientId

### ISSUE THREAD

**Issue by rgmz** [eclipse-vertx/vertx-auth#513]
### Version

4.2.0

### Context

While testing out the new [`OAuth2WebClient`](https://vertx.io/blog/whats-new-in-vert-x-4-2/#web-client-enhancements) with an API that uses the [Resource Owner Password Flow](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-31#section-4.3) and encountered the following exception:
```
java.lang.IllegalStateException: Configuration missing. You need to specify [clientId].
```

This was unexpected because -- as I understand the spec -- the only required elements for RPO are `username` and `password`, which would be provided later in the `withCredentials` block. However, it makes sense if you consider that `OAuth2Options` was previously used for the server and not the client.

### Do you have a reproducer?

A basic reproducer is to create `OAuth2Options` and then call [`.validate()`](https://github.com/vert-x3/vertx-auth/blob/5c295df010a49035cba5a91679dc59af3850fcf4/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/OAuth2Options.java#L610-L627)
```kotlin
val options = OAuth2Options()
    .setFlow(OAuth2FlowType.PASSWORD)
    .setSite("https://example.com/api/")
options.validate()
```

**Comment by pmlopes** [comment]
@rgmz the `clientId` and optionally `clientSecret` are used to identify if we are dealing with a confidential client or not. In other words, this is needed to compute the `Authorization` header for the Oauth2 client and most IdPs will require clients to identify themselves.

Out of curiosity, which server are you using, that allows clients to connect without a `clientId`?

**Comment by rgmz** [comment]
@pmlopes: I'm using the `OAuth2WebClient` as the "Resource Owner", not the "Client". I send my `username` and `password` to the Client (A), which then sends the `username`, `password`, `clientId`, and `clientSecret` to the IdP (B), and returns an access token (C):

```
+----------+
| Resource |
|  Owner   |
|          |
+----------+
     v
     |    Resource Owner
    (A) Password Credentials
     |
     v
+---------+                                  +---------------+
|         |>--(B)---- Resource Owner ------->|               |
|         |         Password Credentials     | Authorization |
| Client  |                                  |     Server    |
|         |<--(C)---- Access Token ---------<|               |
|         |    (w/ Optional Refresh Token)   |               |
+---------+                                  +---------------+
```

In the scenario that the Resource Owner & Client are the same entity you'd require a `clientId`, but having the Client be a separate entity is a common scenario:
* https://developer.okta.com/docs/guides/implement-grant-type/ropassword/main/#grant-type-flow
* https://auth0.com/docs/authorization/flows/resource-owner-password-flow#how-it-works
* https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc
