### ISSUE TITLE
Support a collections of roles in the MongoDB AuthorizationProvider

### ISSUE THREAD

**Issue by bfreuden** [eclipse-vertx/vertx-auth#521]
#### Describe the feature

With a `role` collection containing a `rolename` field (string) and a `permissions` field (array of strings), the MongoDB AuthorizationProvider could propagate role permissions back to the user when the user has that role (like SQL authz providers do if I understood them correctly).

#### Use cases

It is interesting in situations when it is required to decouple roles from permissions associated to those roles.

#### Contribution

I am volunteering for implementing this feature.

**Comment by pmlopes** [comment]
Mongo is maintained in the external org.
