### ISSUE TITLE
[webauthn] unable to instantiate WebAuthOptions

### ISSUE THREAD

**Issue by leleueri** [eclipse-vertx/vertx-auth#527]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

Which version(s) did you encounter this bug ? 

Vertx 4.1.0

### Context

When the class WebAuthnOptions is created, an exception is thrown if a root certificate is invalid (that was the case this morning when the Android Safetynet certificate expired.). Due to this exception, we can't create a new Instance of WebAuthnOptions and by consequences we can't defined an up to date certificate.

Maybe the calls to putRootCertificate should be done into the init method under condition (boolean as constructor parameter). Currently, We inherite the webAuthOption class to avoid this issue.

### Steps to reproduce

1. Create a WebAuthnOptions instance
2. Exception will be thrown due to the putRootCertificate called into the init method.

**Comment by pmlopes** [comment]
Hi @leleueri thanks for the report. We're pushing a release just for this module `4.2.2.1` and `4.1.7.1` that you can use to get your application running again.

**Comment by leleueri** [comment]
Thanks you for fixing this issue so quickly.  :+1:
