### ISSUE TITLE
java.lang.IllegalStateException: Can't change order after route is active

### ISSUE THREAD

**Issue by rzorzorzo** [eclipse-vertx/vertx-auth#568]
### Questions

Do not use this issue tracker to ask questions, instead use one of these [channels](https://vertx.io/community/). Questions will likely be closed without notice.

### Version

4.2.1

### Context

I encountered an exception which looks suspicious while ...

### Do you have a reproducer?

router.get("/static/*").handler(oauth2Handler);
router.route("/api/userinfo/").handler(oauth2Handler);

exception is thrown if more than one routes are set for the same handler.
in the above case in the second line.

this used to work as expected in 3.2.1

### Extra

* Anything that can be relevant such as OS version, JVM version

**Comment by pmlopes** [comment]
This is related to the oauth2 handler trying to ensure that the order of the mount is correct and check if the callback is already setup.

As a work around you can duplicate the oauth2 handler instace and reuse the `Oauth2Auth` provider as that is the one who controls the handshake.
