### ISSUE TITLE
OAuth2Options.setFlow, setClientId etc. deprecated, but needed in OIDC discovery 

### ISSUE THREAD

**Issue by ThorodanBrom** [eclipse-vertx/vertx-auth#577]
### Version

4.3.2

### Context

Some of the methods of the `OAuth2Options` class have been deprecated, like [`setFlow`](https://vertx.io/docs/apidocs/io/vertx/ext/auth/oauth2/OAuth2Options.html#setFlow-io.vertx.ext.auth.oauth2.OAuth2FlowType-), [`setClientId`](https://vertx.io/docs/apidocs/io/vertx/ext/auth/oauth2/OAuth2Options.html#setClientID-java.lang.String-). The documentation specifies to use [`Oauth2Credentials`](https://vertx.io/docs/apidocs/io/vertx/ext/auth/oauth2/Oauth2Credentials.html) instead. However I'm not sure how the credentials can be passed to an OIDC providers' `discover` method, without using the deprecated methods in `OAuth2Options`.

I understand that there will just be a deprecation warning when compiling, but is there any way to avoid it? Or is there another way to pass the credentials when calling `discover`

### Do you have a reproducer?

Running the how-to vert.x [example](https://how-to.vertx.io/web-and-oauth2-oidc/) should throw the warning

**Comment by pmlopes** [comment]
The flow should not be needed for discovery, the idea is that during discovery we collect all allowed flows from the discovery itself. Then when authenticating you specify the flow and if this flow isn't on the discovery list the process completes with an error.

Regarding the client I'd, the deprecation is on a typo. Before was `setClientID` and now we follow the java style `setClientId`.

Indeed we need to update the docs. Do you want to help with a pull request?

**Comment by ThorodanBrom** [comment]
Hello @pmlopes 

Many thanks for your reply, I've understood the issue. The `setClientId`, `setClientID` thing confused me a little! The [Vert.x OAuth2 docs](https://vertx.io/docs/vertx-auth-oauth2/java/#_openid_connect_discovery) were clear when it came to discovery, I should have checked them out before making the issue.

I'll be happy to take a shot at making a PR for the vertx-howtos code update. The Vert.x OAuth2 docs may also need updating since `OAuth2Options.setFlow` is used everywhere.

Regarding the `authenticate()` method, would it better to change the docs to use the `authenticate(Credentials)` parameter instead of the `authenticate(JsonObject)`?

As far as I understood the code in [OAuth2AuthProviderImpl](https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2AuthProviderImpl.java), when using the JsonObject method, the flow is implied from the key in the JSON, whereas 
- using `Oauth2Credentials`, you explicitly set the flow (like how it was done in OAuth2Options) and the other credentials,
- using `TokenCredentials`, you set the token and (I think) the flow is implicit
