### ISSUE TITLE
Feature: Do not require private key for JWT if not planning to sign tokens?

### ISSUE THREAD

**Issue by plombardi89** [eclipse-vertx/vertx-auth#59]
Right now the JWT module requires a private key for asymetric keys in order to be used, however, if you're only interested in decoding and verifying a key then this is an unnecessary additional piece of security data that needs to be stored in the key store. The piece of code responsible for this is located here:

``` java
X509Certificate certificate = getCertificate(keyStore, alg);
PrivateKey privateKey = getPrivateKey(keyStore, keyStorePassword, alg);
if (certificate != null && privateKey != null) {
  tmp.put(alg, new CryptoSignature(alias.get(alg), certificate, privateKey));
} else {
  log.info(alg + " not available");
}
```

Can the requirement that a private key be present be lifted?

**Comment by pmlopes** [comment]
Thanks, this is a good idea and it is already required for openid-connect (see #58) where only public keys are provided.
