### ISSUE TITLE
ShiroAuthService seems to autologout after 5 seconds.

### ISSUE THREAD

**Issue by bckfnn** [eclipse-vertx/vertx-auth#6]
This is mostly a query to see if I have misunderstood the behaviour, but it seems that refreshLoginSession must be called immediately after a login, otherwise the session is timeout'd the first time the reaper is run.

Is it also intended that refreshLoginSession should be called manually to keep the login session alive? I would have guessed that calls to hasPermission() and hasRole() would keep the login session alive as well.

**Comment by purplefox** [comment]
Good catch. Should be fixed now in master.
