### ISSUE TITLE
Docs link to legacy repository

### ISSUE THREAD

**Issue by lukasalexanderweber** [eclipse-vertx/vertx-auth#616]
Looking at https://vertx.io/docs/vertx-auth-jwt/java/ I wondered why the vertx-auth-jwt package has only 2 stars.

Then I noticed that it linkes to https://github.com/vert-x3/vertx-auth.

I don't know where this can be changed, otherwise I would've opened a PR.

**Comment by pmlopes** [comment]
Fixed by: https://github.com/vertx-web-site/vertx-web-site.github.io/pull/143
