### ISSUE TITLE
OAuth2AuthHandler callback allows unauthorized access

### ISSUE THREAD

**Issue by amoAHCP** [eclipse-vertx/vertx-auth#65]
### Version
- vert.x core: 3.2.1
- vert.x auth: 3.2.1
### Context

http://localhost:8080/callback?redirect_uri=/private/somepage/test leads to unauthorized acces while http://localhost:8080/private/somepage/test starts auth process correctly.

Output:
Welcome to the protected resource! :

{
  "error" : "bad_verification_code",
  "error_description" : "The code passed is incorrect or expired.",
  "error_uri" : "https://developer.github.com/v3/oauth/#bad-verification-code"
}
### Do you have a reproducer?

https://gist.github.com/amoAHCP/b3509d859096952caf76f46665835525

**Comment by pmlopes** [comment]
This issue is not reproducible anymore on 3.3.0-SNAPSHOT which is going to be released next month.
