### ISSUE TITLE
Wrong initialization of  jwtOptions field in OAuth2Options

### ISSUE THREAD

**Issue by weery28** [eclipse-vertx/vertx-auth#663]
### Version

4.4.1

### Context

I encountered an exception which looks suspicious while create more than one instance of OAuth2Options. 
jwtOptions initialized by object in static field, then we have the same object in every  OAuth2Options instance.

https://github.com/eclipse-vertx/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/OAuth2Options.java#L51

This line should not exist. A new instance should be created here:

https://github.com/eclipse-vertx/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/OAuth2Options.java#L174

**Comment by vietj** [comment]
@weery28 I need a contributor agreement to be signed on the PR

**Comment by tsegismont** [comment]
Duplicated by https://github.com/eclipse-vertx/vertx-auth/issues/676
