### ISSUE TITLE
vertx mongo auth js is broken

### ISSUE THREAD

**Issue by rtv2222** [eclipse-vertx/vertx-auth#68]
### Version
- vert.x core:3.2.1
- vert.x auth:3.2.1
### Context

The Javascript example for vertx mongo auth just does not work.
### Do you have a reproducer?

https://groups.google.com/forum/#!topic/vertx/AfjHVJy4wtk has already raised the issue. I am repeating it here to see if it helps.
### Steps to reproduce

Just follow the documentation to create a JS vertx mongo auth client. Call to authenticate fails with a TypeErrpr. https://github.com/markus-simon/auth example is linked from the Google Groups link above

**Comment by pmlopes** [comment]
This issue was moved to vert-x3/vertx-lang-js#53
