### ISSUE TITLE
JWTAuth.create(...) skip parameter is a bit too eager when logic invoked in JWTAuthHandlerImpl

### ISSUE THREAD

**Issue by plombardi89** [eclipse-vertx/vertx-auth#69]
### Version
- vert.x core: 3.2.1
- vert.x auth: 3.2.1
### Context

The skip parameter is too eager. The code checks for whether or not the skip string contains the request string:

``` java
if (skip != null && skip.contains(request.path())) {
        context.next();
        return;
}
```

If the skip String is configured such as '/health' and the `request.path()` == '/' then the skip execution always occurs which is probably not what was intended?

I'm not sure what the best behavior here is... My suggestion would be to make it so that if someone specifies a skip that does not end in \* or /\* then the check should be for equality, for example, only skip if `request.path().equals(skip)`. If the skip String is, for example, instead /health\* or /health/\* then it should should work as `request.path().startsWith(skip)`. Perhaps the inverse should be true if someone specifies a skip string preceded by \* or */. 
### Do you have a reproducer?

Not public at the moment. Trivial to see the problem though.
### Steps to reproduce
1. 
2. 
3. 
4. 
### Extra

I worked around the issue by sub classing the JWTAuthHandlerImpl and writing my own skip implementation that works for my specific situation.

**Comment by pmlopes** [comment]
This issue was moved to vert-x3/vertx-web#394
