### ISSUE TITLE
OAuth getToken result.failed() information is inconsistent when sending invalid code as payload

### ISSUE THREAD

**Issue by eduardolundgren** [eclipse-vertx/vertx-auth#76]
### Version
- vert.x core: 3.3.0
- vert.x auth: 3.3.2
### Context

OAuth getToken never flags `result.failed()` as `true` for invalid code sent. I am testing this with GitHub provider. Note in the debugger image that the `result.failed()` is always `false` and docs (http://vertx.io/docs/vertx-auth-oauth2/java/) says it should be `true` on error.

``` java
oauth2.getToken(new JsonObject().put("code", code).put("redirect_uri", "http://localhost:8080/callback"), res -> {
  if (res.failed()) {
    // error, the code provided is not valid
  } else {
    // save the token and continue...
  }
});
```
### Do you have a reproducer?

<img width="483" alt="screen shot 2016-07-13 at 2 40 47 pm" src="https://cloud.githubusercontent.com/assets/113087/16820810/e3802aa2-4907-11e6-8d36-6bc1054e5c4e.png">
<img width="690" alt="screen shot 2016-07-13 at 2 41 04 pm" src="https://cloud.githubusercontent.com/assets/113087/16820811/e381936a-4907-11e6-9e7a-d799ad6ed1e6.png">

**Comment by pmlopes** [comment]
The token is not inspected for the error handling, just the http data flow. OAuth2 tokens are opaque strings. We can try to improve the usability by looking up the fields:
- error
- error_description (optional)
- error_code (optional)

And take that also in account when dealing with the success/failure state.

**Comment by eduardolundgren** [comment]
Thanks @pmlopes
