### ISSUE TITLE
OAuth2 final redirect should be a HTTP redirect

### ISSUE THREAD

**Issue by pmlopes** [eclipse-vertx/vertx-auth#77]
Currently the final redirect is handled internally, however this can cause problems if a user refreshes the html page since a new token request is done and invalidates the token.

Doing a HTTP redirect (would enforce users use a session handler) so state is preserved and no issues would happen due to refresh page.

**Comment by pmlopes** [comment]
This issue was moved to vert-x3/vertx-web#457

**Comment by cescoffier** [comment]
Marked it as invalid because it has been moved.
