### ISSUE TITLE
OAuth getToken don't response when java.net.UnknownHostException is thrown

### ISSUE THREAD

**Issue by atsusugi** [eclipse-vertx/vertx-auth#81]
### Version
- vert.x core:3.3.2
- vert.x auth:3.3.2
### Context

OAuth getToken can't set exceptionHandler to HttpClientRequest and don't call callback method when exception is thrown in HttpClientRequest.
When java.net.UnknownHostException was thrown (Google's OAuth API Server downed), my app couldn't response anything to browser.

**Comment by tsegismont** [comment]
Could you provide a simple reproducer? Thanks

**Comment by atsusugi** [comment]
could you execute blow steps?
1. turn off WiFi, (no internet access is important!)
2. run below code and access to "http://localhost:8080/callback" in browser. 

java.net.UnknownHostException will be thrown and browser will wait the response for a while.

``` java
public class Test {
  public static void main(String[] args) {
    Vertx.vertx().deployVerticle(new Verticle());
  }

  static class Verticle extends AbstractVerticle {
    @Override
    public void start() throws Exception {
      Router router = Router.router(vertx);
      router.route("/callback").handler(ctx -> {
        OAuth2Auth oauth2 = OAuth2Auth.create(vertx, OAuth2FlowType.AUTH_CODE, new OAuth2ClientOptions()
          .setClientID("CLIENT_ID")
          .setClientSecret("CLIENT_SECRET")
          .setSite("https://accounts.google.com")
          .setTokenPath("https://www.googleapis.com/oauth2/v3/token")
          .setAuthorizationPath("/o/oauth2/auth")
        );
        oauth2.getToken(new JsonObject().put("code", "dummy"), res -> {
          ctx.response().write("called").end();
        });
      });
      vertx.createHttpServer().requestHandler(router::accept).listen(8080);
    }
  }
}
```

**Comment by tsegismont** [comment]
In this part:

``` java
oauth2.getToken(new JsonObject().put("code", "dummy"), res -> {
          ctx.response().write("called").end();
        });
```

You should check if the call succeded or failed.

``` java
oauth2.getToken(new JsonObject().put("code", "dummy"), res -> {
  if (ar.succeeded()) {
          ctx.response().write("called").end();
} else {
// send error response to the browser
}
        });
```

**Comment by atsusugi** [comment]
``` java
res -> {
  ctx.response().write("called").end();
}
```

in your environment, is this block called?
in my environment, it is never called, 

so, is your below code meaningless?
because check logic will not be called, when UnknownHostException is thrown.

``` java
if (ar.succeeded()) {
          ctx.response().write("called").end();
} else {
// send error response to the browser
}
```

**Comment by tsegismont** [comment]
To be honest I had not tried, I just saw that the async result status was
not checked, so my first assumption was that the problem lied there. With
your latest findings, I believe now that the exception is not managed and
correctly in the oauth2 impl, and the handler never called. Will check.

2016-08-27 11:21 GMT+02:00 atsusugi notifications@github.com:

**Comment by tsegismont** [comment]
@atsusugi sent PR

**Comment by atsusugi** [comment]
thank you!
