### ISSUE TITLE
Control of configuration for the underlying HttpClient

### ISSUE THREAD

**Issue by greggigon** [eclipse-vertx/vertx-auth#85]
Hi
On line 
https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2API.java#L114 

`client = provider.getVertx().createHttpClient(new HttpClientOptions()
          .setSsl(isSecure)
          .setDefaultHost(host)
          .setDefaultPort(port));`

new client is created for the request. It would be nice to be able to control the client configuration from the overall OAuth2ClientOptions. 

For example: 

`client = provider.getVertx().createHttpClient(config);`

Wasn't that the intention #56 and #57 ?

At the moment I can't ignore SSL errors in my test environment or add keystore for the client.

Greg

**Comment by pmlopes** [comment]
OAuth2ClientOptions extends HttpClientOptions, i guess that we missed that line and instead of using a new HttpClientOptions we should have used the global config

**Comment by greggigon** [comment]
I guess the fix would go out in the next release?
What would you recommend as a workaround for now? HttpClient seems to ignore my truststore set via system properties:

`java -Djavax.net.ssl.turustStore=./tmpkeystore -Djavax.net.ssl.trustStorePassword=changeit App`
