### ISSUE TITLE
Remove support of "none" for encryption, or put behind a switch

### ISSUE THREAD

**Issue by DanielJoyce** [eclipse-vertx/vertx-auth#89]
In general this is considered a fault of the spec. 

An opinionated stance should be taken on this issue. Its frankly dumb this option made it into the spec.

**Comment by pmlopes** [comment]
`none` is only allowed IFF there is no key provided:

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWT.java#L175
