### ISSUE TITLE
JWTAuthProviderTest.testGenerateNewToken fails repeatedly

### ISSUE THREAD

**Issue by tsegismont** [eclipse-vertx/vertx-auth#94]
https://vertx.ci.cloudbees.com/job/vert.x3-auth/1347/

More details in https://vertx.ci.cloudbees.com/job/vert.x3-auth/1368/testReport/io.vertx.ext.auth.test.jwt/JWTAuthProviderTest/testGenerateNewToken/

**Comment by pmlopes** [comment]
Fixed in fd2cb1b758c1e6e270daa7fe37d362108da86c83
