### ISSUE TITLE
Decoding UNSECURE token fails, as none of the algorithms match JWT Header

### ISSUE THREAD

**Issue by greggigon** [eclipse-vertx/vertx-auth#96]
### Version

* vert.x core: 3.3.3
* vert.x auth: 3.3.3

### Context

Decoding token with JWT created with no Keystore fails. This is because unsecured is set to true and cryptoMap is empty.

I'm not sure if it is a bug or a concision design decisions. 

Not validating a signature in production is another problem in itself, I do realize that, however, I'm using JWT class directly as I have a very specific needs for AuthProvider and AuthHandler. 

I stumbled across this issue unit testing my AuthProvider.
The interesting line is [https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWT.java#L187](https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWT.java#L187)

Perhaps it should read: 

`if (!unsecure && crypto == null) {
    throw new RuntimeException("Algorithm not supported");
}
`

Also, the entire signature validation block would have to be skipped.
Any thoughts ?

**Comment by pmlopes** [comment]
JWT without keystore is a encoder/decoder only for unsafe tokens e.g.: `alg: "none"`

If you use other algorithm then we cannot validate since no keys have been loaded and that is not the definition of unsafe token.

**Comment by greggigon** [comment]
OK, I see. Thanks.
